export function inspectThicknessDialog({state,openDialog,element,emit}){
  const bodyId=state.selectedIds[0],top=structuredClone(state.selectedTopology),openedRevision=state.revision;
  const d=openDialog('指定位置壁厚','选择实体表面的真实点，并给出向材料内部的方向；也可选两张相对平行面。结果仅说明该位置第一段连续材料。');
  const form=element('form',{class:'parameter-form'}),mode=element('select',{name:'thicknessMode','aria-label':'壁厚检查模式'}),result=element('pre',{class:'info-content fit-result','aria-live':'polite'});
  for(const [value,label] of [['ray','表面点 + 向内方向'],['faces','两张平行面']])mode.append(element('option',{value},label));
  const modeLabel=element('label',{class:'form-field wide'});modeLabel.append(element('span',{},'检查模式'),mode);form.append(element('p',{class:'wide'},`实体：${state.bodies.find(body=>body.id===bodyId)?.name||'未选择'} · 已锁定`),modeLabel);
  const controls={};for(const [key,label,value]of [['x','表面点 X',top?.point?.[0]],['y','表面点 Y',top?.point?.[1]],['z','表面点 Z',top?.point?.[2]],['dx','向内方向 X',0],['dy','向内方向 Y',0],['dz','向内方向 Z',1],['faceAId','第一面 ID',top?.ids?.[0]],['faceBId','第二面 ID',top?.ids?.[1]]]){const wrap=element('label',{class:'form-field','data-field':key}),input=element('input',{type:'number',step:'any',name:key,value:value??'','aria-label':label});wrap.append(element('span',{},label),input);controls[key]=input;form.append(wrap);}
  const refresh=()=>{for(const key of ['dx','dy','dz','faceAId','faceBId'])form.querySelector(`[data-field="${key}"]`).hidden=mode.value==='ray'?key.startsWith('face'):key.startsWith('d');};mode.addEventListener('change',refresh);refresh();
  const directionChoice=element('select',{'aria-label':'测厚向内方向'});for(const [value,label]of [['0,0,1','+Z'],['0,0,-1','−Z'],['1,0,0','+X'],['-1,0,0','−X'],['0,1,0','+Y'],['0,-1,0','−Y']])directionChoice.append(element('option',{value},label));
  const directionLabel=element('label',{class:'form-field wide'});directionLabel.append(element('span',{},'向内方向'),directionChoice);form.append(directionLabel);directionChoice.addEventListener('change',()=>directionChoice.value.split(',').forEach((value,i)=>controls[['dx','dy','dz'][i]].value=value));
  for(const key of ['dx','dy','dz']){controls[key].type='hidden';controls[key].closest('label').hidden=true;}
  mode.addEventListener('change',()=>{directionLabel.hidden=mode.value!=='ray';for(const key of ['dx','dy','dz'])controls[key].closest('label').hidden=true;});
  for(const key of ['faceAId','faceBId']){const old=controls[key],choice=element('select',{name:key,'aria-label':key==='faceAId'?'第一面':'第二面'});old.replaceWith(choice);controls[key]=choice;}
  if(bodyId)window.webcad.api.queryGeometry({context:window.webcad.api.getState().context,bodyId,kind:'face',limit:100,requireUnique:false}).then(response=>{if(!form.isConnected)return;if(response.status==='failed'){result.textContent=response.error.message;return;}for(const key of ['faceAId','faceBId']){for(const face of response.items||[])controls[key].append(element('option',{value:String(face.topologyId)},`面 ${face.topologyId} · ${face.geomType}`));const picked=top?.type==='face'?top.ids?.[key==='faceAId'?0:1]:undefined;if(picked!==undefined)controls[key].value=String(picked);}const pickedFace=response.items?.find(face=>face.topologyId===top?.ids?.[0]),normal=pickedFace?.normal;if(normal?.length===3){const value=normal.map(v=>-v).join(',');directionChoice.append(element('option',{value},'所选面向内法向'));directionChoice.value=value;directionChoice.dispatchEvent(new Event('change'));}}).catch(error=>result.textContent=error.message);
  const submit=element('button',{type:'submit',class:'primary'},'检查厚度');form.append(submit);d.append(form,result);
  form.addEventListener('submit',async event=>{event.preventDefault();submit.disabled=true;try{if(state.revision!==openedRevision)throw new Error('模型已变化，请重新选择位置检查。');const number=key=>{const value=controls[key].value;if(!value.trim()||!Number.isFinite(Number(value)))throw new Error(`${controls[key].getAttribute('aria-label')} 需要有效数值`);return Number(value);};const input={bodyId,mode:mode.value,point:['x','y','z'].map(number)};if(mode.value==='ray')input.direction=['dx','dy','dz'].map(number);else {input.faceAId=number('faceAId');input.faceBId=number('faceBId');}const report=await emit('inspectThickness',input);if(report?.status!=='read')return;result.dataset.revision=String(report.context.revision);result.textContent=`厚度：${report.thicknessMm.toFixed(6)} mm\n进入点：${report.entryPoint.map(n=>n.toFixed(4)).join(', ')}\n离开点：${report.exitPoint.map(n=>n.toFixed(4)).join(', ')}\n方向：${report.direction.map(n=>n.toFixed(5)).join(', ')}\n来源修订：r${report.context.revision}\n范围：指定位置的第一段连续材料；不是整件最小壁厚。`;}catch(error){result.textContent=error.message;}finally{submit.disabled=false;}});
 }
