export function measureRelationDialog({state,openDialog,element,emit}){
  const openedRevision=state.revision,d=openDialog('精确关系测量','中心距、有限几何最短距离、两轴夹角与法向距离分别报告；不会把无限支撑平面当成零件间隙。');
  const form=element('form',{class:'parameter-form'}),mode=element('select',{'aria-label':'关系测量方式'}),result=element('pre',{class:'info-content fit-result','aria-live':'polite'});
  for(const [id,label]of [['shortest','有限对象最短距离'],['centerDistance','两圆心中心距'],['axisAlignment','两圆轴夹角 / 同轴偏差'],['pointFace','点到有限面'],['parallelFaces','平行面法向距离']])mode.append(element('option',{value:id},label));
  const modeLabel=element('label',{class:'form-field wide'});modeLabel.append(element('span',{},'测量方式'),mode);form.append(modeLabel);
  const refControl=(label,selectedId)=>{const section=element('fieldset',{class:'relation-ref'}),legend=element('legend',{},label),body=element('select',{'aria-label':`${label}实体`}),kind=element('select',{'aria-label':`${label}类型`}),topology=element('select',{'aria-label':`${label}拓扑`});for(const item of state.bodies)body.append(element('option',{value:item.id},item.name||item.id));body.value=selectedId||state.bodies[0]?.id||'';for(const [id,name] of [['body','整个实体'],['edge','边'],['face','面']])kind.append(element('option',{value:id},name));const refresh=async()=>{topology.replaceChildren();topology.hidden=kind.value==='body';if(topology.hidden||!body.value)return;const filter=mode.value==='centerDistance'||mode.value==='axisAlignment'?{curveType:'circle'}:{};const response=await window.webcad.api.queryGeometry({context:window.webcad.api.getState().context,bodyId:body.value,kind:kind.value,filter,limit:100,requireUnique:false});if(response.status==='failed'){result.textContent=response.error.message;return;}for(const item of response.items||[])topology.append(element('option',{value:String(item.topologyId)},`${item.topologyId} · ${item.geomType}${item.radiusMm?` · R${item.radiusMm.toFixed(3)}`:''}`));};body.addEventListener('change',refresh);kind.addEventListener('change',refresh);section.append(legend,body,kind,topology);form.append(section);return {section,body,kind,topology,refresh,read(){if(!body.value)throw new Error('请选择实体');if(kind.value!=='body'&&!topology.value)throw new Error(`${label}没有可用的精确拓扑`);return {bodyId:body.value,kind:kind.value,...(kind.value==='body'?{}:{topologyId:Number(topology.value)})};}};};
  const first=refControl('第一对象',state.selectedIds[0]),second=refControl('第二对象',state.selectedIds[1]||state.selectedIds[0]);
  const pointFields=['X','Y','Z'].map((axis,i)=>{const label=element('label',{class:'form-field'}),input=element('input',{type:'number',step:'any',value:state.selectedTopology?.point?.[i]??'','aria-label':`点 ${axis} mm`});label.append(element('span',{},`点 ${axis} mm`),input);form.append(label);return {label,input};});
  const refresh=()=>{const circle=['centerDistance','axisAlignment'].includes(mode.value),face=mode.value==='parallelFaces',point=mode.value==='pointFace';first.section.hidden=point;first.kind.value=circle?'edge':face?'face':'body';second.kind.value=circle?'edge':face||point?'face':'body';for(const entry of pointFields)entry.label.hidden=!point;first.refresh();second.refresh();};mode.addEventListener('change',refresh);
  const submit=element('button',{type:'submit',class:'primary'},'测量');form.append(submit);d.append(form,result);refresh();
  form.addEventListener('submit',async event=>{event.preventDefault();submit.disabled=true;try{if(openedRevision!==state.revision)throw new Error('模型已变化，请重新选择关系目标。');const input={mode:mode.value,...(mode.value==='pointFace'?{face:second.read(),pointWorld:pointFields.map(({input})=>{if(!input.value.trim())throw new Error('请填写点的世界坐标');return Number(input.value);})}:{first:first.read(),second:second.read()})};const report=await emit('measureRelation',input);if(report?.status!=='read')return;result.dataset.revision=String(report.context.revision);result.textContent=`${mode.options[mode.selectedIndex].textContent}\n${report.distanceMm!==undefined?`有限最短距离：${report.distanceMm.toFixed(6)} mm\n`:''}${report.centerDistanceMm!==undefined?`圆心距：${report.centerDistanceMm.toFixed(6)} mm\n轴夹角：${report.axisAngleDeg.toFixed(6)}°\n同轴偏差：${report.coaxialDeviationMm===null?'轴不平行':report.coaxialDeviationMm.toFixed(6)+' mm'}\n`:''}${report.normalDistanceMm!==undefined?`法向距离：${report.normalDistanceMm.toFixed(6)} mm\n有限面最短距离：${report.shortestDistanceMm.toFixed(6)} mm\n`:''}${report.witnessPoints?`见证点：${report.witnessPoints.map(point=>point.map(n=>n.toFixed(4)).join(', ')).join(' ↔ ')}\n`:''}来源修订：r${report.context.revision}`;}catch(error){result.textContent=error.message;}finally{submit.disabled=false;}});
 }
