import test from 'node:test';
import assert from 'node:assert/strict';
import {writeGeneratedFile} from '../scripts/generated-file-write.mjs';
const openError=()=>Object.assign(new Error('temporary open failure'),{code:'UNKNOWN',errno:-4094,syscall:'open'});

test('generated writes retry one observed Windows open failure with identical bytes and options',async()=>{
 const calls=[],waits=[],warnings=[],data=Buffer.from('generated bytes');
 await writeGeneratedFile('output.json',data,'utf8',{platform:'win32',write:async(...args)=>{calls.push(args);if(calls.length===1)throw openError();},wait:async ms=>waits.push(ms),warn:text=>warnings.push(text)});
 assert.equal(calls.length,2);assert.deepEqual(calls[0],calls[1]);assert.strictEqual(calls[1][1],data);assert.deepEqual(waits,[150]);assert.equal(warnings.length,1);
});
test('persistent failure is preserved after one retry and unrelated failures are never retried',async()=>{
 const second=openError();let attempts=0;
 await assert.rejects(writeGeneratedFile('output.json','data',undefined,{platform:'win32',write:async()=>{attempts++;throw attempts===1?openError():second;},wait:async()=>{},warn:()=>{}}),error=>error===second);assert.equal(attempts,2);
 for(const [platform,error]of [['linux',openError()],['win32',Object.assign(openError(),{syscall:'write'})],['win32',Object.assign(openError(),{code:'EACCES'})],['win32',Object.assign(openError(),{code:'ENOSPC'})]]){
  attempts=0;await assert.rejects(writeGeneratedFile('output.json','data',undefined,{platform,write:async()=>{attempts++;throw error;},wait:async()=>assert.fail('unexpected retry'),warn:()=>assert.fail('unexpected warning')}),err=>err===error);assert.equal(attempts,1);
 }
});
