import assert from 'node:assert/strict';
import fs from 'node:fs';
import init from 'replicad-opencascadejs';
import * as cad from 'replicad';
import {CadKernel} from '../src/cad-kernel.js';
import {diagnoseSurface,surfaceTrim} from '../src/surface-repair.js';
import {extractFaceBoundary} from '../src/reference-curves.js';
const oc=await init({wasmBinary:fs.readFileSync(new URL('../node_modules/replicad-opencascadejs/dist/replicad_single.wasm',import.meta.url))});
const kernel=new CadKernel(oc);
const f=(id,op,params={},refs=[])=>({id,op,params,refs,name:id});
const box=f('box','box',{width:10,depth:10,height:10});
const run=features=>kernel.rebuild({version:1,features,imports:{},hidden:[]});
let out=await run([box,f('section','planeSection',{plane:'XY',offset:5},['box'])]);
assert.equal(out.bodies.length,2);assert.equal(out.bodies[1].edges.length,4);assert.equal(out.bodies[1].indices.length,0);
out=await run([box,f('boundary','faceBoundary',{faceId:0},['box'])]);
assert.equal(out.bodies.length,2);assert.equal(out.bodies[1].edges.length,4);
out=await run([box,f('sewn','sewFaces',{makeSolid:true},['box'])]);
assert.equal(out.bodies.length,1);assert.equal(out.bodies[0].solidCount,1);assert.ok(Math.abs(out.bodies[0].volume-1000)<1e-6);
const exported=await kernel.export('step');
const restored=await cad.importSTEP(new Blob([exported.data]));assert.ok(Math.abs(cad.measureVolume(restored)-1000)<1e-6);restored.delete();
const source=cad.makeBox([0,0,0],[10,10,10]);
const faces=source.faces,face=faces.find(face=>Math.abs(face.center.z)<1e-8);
const tool=cad.makeBox([0,0,-1],[4,4,1]);
const inside=surfaceTrim({face,tool},cad),outside=surfaceTrim({face,tool,mode:'cut'},cad);
assert.ok(Math.abs(cad.measureArea(inside)-16)<1e-6);assert.ok(Math.abs(cad.measureArea(outside)-84)<1e-6);
const remote=cad.makeBox([20,20,20],[21,21,21]);assert.throws(()=>surfaceTrim({face,tool:remote},cad),/空/);
const open=cad.makeCompound(faces.slice(0,5));assert.equal(diagnoseSurface(open,cad).freeEdges,4);
[inside,outside,tool,remote,open,...faces,source].forEach(x=>x.delete());
console.log('PASS reference integration: wire display, preserved source, sewn volume + STEP, trim areas, empty rejection, free edges');
const outerCylinder=cad.makeCylinder(5,2),innerCylinder=cad.makeCylinder(2,2),ring=outerCylinder.cut(innerCylinder);
const ringFaces=ring.faces,topIndex=ringFaces.findIndex(face=>face.geomType==='PLANE'&&Math.abs(face.center.z-2)<1e-7);
const allBoundary=extractFaceBoundary(ring,topIndex,cad),outerBoundary=extractFaceBoundary(ring,topIndex,cad,{boundary:'outer'});
const allEdges=allBoundary.edges,outerEdges=outerBoundary.edges;
assert.equal(allEdges.length,2);assert.equal(outerEdges.length,1);
assert.ok(Math.abs(outerEdges[0].length-10*Math.PI)<1e-6);
assert.ok(Math.abs(cad.measureVolume(ring)-42*Math.PI)<1e-6);
[...allEdges,...outerEdges,...ringFaces,allBoundary,outerBoundary,ring,innerCylinder,outerCylinder].forEach(x=>x.delete());
console.log('PASS explicit outer-only boundary excludes hole without modifying source');
