import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import net from 'node:net';
import {spawn} from 'node:child_process';
import {randomBytes} from 'node:crypto';
import init from 'replicad-opencascadejs';
import {CadKernel} from '../src/cad-kernel.js';
import {createServicesClient} from '../src/services/client.js';
import {compileRemoteFeature} from '../src/services/remote-executor.js';
import {installCompiledCandidate} from '../src/services/geometry-exchange.js';
import {encodeProjectV3,decodeProject} from '../src/project-container.js';
test('real HTTP/native result installs at the original recipe, cold-opens offline and invalidates upstream changes',async()=>{
 const host=process.env.WEBCAD_SERVICES_TEST_HOST,logo=process.env.WEBCAD_SERVICES_TEST_LOGO_WORKER,worker=process.env.WEBCAD_NATIVE_WORKER,proof=process.env.WEBCAD_NATIVE_ACCEPTANCE,root=process.env.WEBCAD_NATIVE_TEST_ROOT;assert.ok(host&&logo&&worker&&proof&&root,'Actual Host/Logo/native binaries and a tested kernel pair are required');
 await fs.mkdir(root,{recursive:true});const data=await fs.mkdtemp(path.join(root,'compute-'));const reserve=net.createServer();await new Promise(r=>reserve.listen(0,'127.0.0.1',r));const port=reserve.address().port;await new Promise(r=>reserve.close(r));const credential=randomBytes(32).toString('hex');
 const child=spawn(host,['--console'],{windowsHide:true,stdio:['ignore','ignore','pipe'],env:{...process.env,WEBCAD_SERVICES_DATA_ROOT:data,WEBCAD_SERVICES_LOGO_WORKER:logo,WEBCAD_SERVICES_TOKEN:credential,WEBCAD_SERVICES_DEV_HTTP:`http://127.0.0.1:${port}/`,WEBCAD_SERVICES_OCCT_WORKER:worker,WEBCAD_SERVICES_NATIVE_ACCEPTANCE:proof,WEBCAD_SERVICES_PIPE_NAME:'WebCADServices-native-test'}});let error='';child.stderr.on('data',chunk=>{error=(error+chunk).slice(-4096);});const stop=async()=>{if(child.exitCode===null&&child.signalCode===null){child.kill();await new Promise(r=>child.once('exit',r));}};
 const client=createServicesClient({config:{url:`http://127.0.0.1:${port}/api.ashx`,enabled:true},credential});let engine,cold,edited;
 try{
  const began=Date.now();for(;;){try{await client.capabilities();break;}catch(e){if(child.exitCode!==null)throw new Error(error);if(Date.now()-began>15000)throw e;await new Promise(r=>setTimeout(r,100));}}
  const wasm=await fs.readFile(new URL('../node_modules/replicad-opencascadejs/dist/replicad_single.wasm',import.meta.url)),oc=await init({wasmBinary:wasm});engine=new CadKernel(oc);
  const doc={version:2,documentId:'native-acceptance-doc',features:[{id:'source',op:'box',params:{width:10,depth:8,height:3},refs:[]},{id:'shift',op:'transform',params:{x:2,y:-3,z:1},refs:['source']}],imports:{}},context={documentId:doc.documentId,documentInstanceId:'native-test-instance',expectedRevision:7};await engine.rebuild(doc);
  const frozen=engine.serializeFeatureShape('source').data,complexity=engine.sourceComplexity('source',0);assert.equal(complexity.bytes,frozen.length);assert.equal(complexity.faces,6);assert.equal(complexity.solids,1);assert.equal(complexity.holes,0);assert.deepEqual(engine.serializeFeatureShape('source').data,frozen);const bytes=frozen,candidate=await compileRemoteFeature(doc,'shift',bytes,context,{allowUpload:true,client});
  const installed=installCompiledCandidate(doc,{manifest:candidate.manifest,bytes:candidate.geometryBytes,context,recipeFingerprint:candidate.recipeFingerprint});assert.equal(installed.features[1].op,'transform');assert.deepEqual(installed.features[1].params,doc.features[1].params);assert.deepEqual(installed.features[1].refs,['source']);const built=await engine.rebuild(installed);assert.deepEqual(built.compiledReuse,['shift']);assert.equal(built.bodies[0].volume,240);
  await fs.writeFile(path.join(data,'manifest.json'),JSON.stringify(candidate.manifest,null,2));const packet=encodeProjectV3(installed);await fs.writeFile(path.join(data,'accepted.webcad'),packet);
  const reboundContext={...context,documentInstanceId:'new-instance',expectedRevision:8},rebound=await compileRemoteFeature(doc,'shift',bytes,reboundContext,{allowUpload:true,client});assert.equal(rebound.manifest.jobId,candidate.manifest.jobId);assert.equal(rebound.manifest.computeCacheHit,true);assert.equal(rebound.manifest.documentInstanceId,reboundContext.documentInstanceId);assert.equal(rebound.manifest.expectedRevision,8);assert.equal(rebound.manifest.geometryArtifact.sha256,candidate.manifest.geometryArtifact.sha256);installCompiledCandidate(doc,{manifest:rebound.manifest,bytes:rebound.geometryBytes,context:reboundContext,recipeFingerprint:rebound.recipeFingerprint});
  const corruptSource=await client.upload(new File(['deliberately invalid BRep fault fixture'],'invalid.brep'),{kind:'brep'}),faultPayload={requestId:'native-fault',documentId:context.documentId,documentInstanceId:context.documentInstanceId,expectedRevision:context.expectedRevision,featureId:'fault',operation:'transform',schemaVersion:'1.0',semanticVersion:'transform.translation-1.0',inputs:[{assetId:corruptSource.assetId,sha256:corruptSource.sha256,role:'source',sourceFeatureId:'fault-source'}],placementSnapshot:null,selectionIntent:{kind:'whole-source'},params:{x:1,y:0,z:0},strategy:'translation',requiredResultFormat:'occt-text-brep-v1',recipeFingerprint:'fault-fixture'};
  const fault=await client.submit('compute/jobs',faultPayload,'native-fault-key');await assert.rejects(client.wait(fault),error=>error.code==='OCCT_FAILURE'&&error.job.execution==='failed'&&error.stage==='read-brep'&&error.jobId===fault.jobId&&error.commitState==='notCommitted');assert.equal((await client.submit('compute/jobs',faultPayload,'native-fault-key')).jobId,fault.jobId);await assert.rejects(client.submit('compute/jobs',{...faultPayload,requestId:'new-id-same-failed-input'},'native-fault-new-key'),{code:'KNOWN_INPUT_FAILED'});assert.equal((await client.capabilities()).protocolVersion,'1.0','A failed worker cannot terminate Host');
  await stop();const reopened=await decodeProject(packet);cold=new CadKernel(oc);const operation=cold.operation.bind(cold);cold.operation=(feature,...args)=>{if(feature.id==='shift')throw new Error('Saved native checkpoint must not recalculate this operation');return operation(feature,...args);};const opened=await cold.rebuild(reopened);assert.deepEqual(opened.compiledReuse,['shift']);assert.equal(opened.bodies[0].volume,240);
  const extended={...reopened,features:[...reopened.features,{id:'after',op:'transform',params:{x:1},refs:['shift']}]};const local=await cold.rebuild(extended);assert.equal(local.bodies[0].id,'after');assert.equal(local.bodies[0].bounds.min[0],3);
  cold.operation=operation;await cold.rebuild(doc);const redo=await cold.rebuild(reopened);assert.deepEqual(redo.compiledReuse,['shift']);
  assert.throws(()=>installCompiledCandidate(doc,{manifest:candidate.manifest,bytes:candidate.geometryBytes,context:{...context,expectedRevision:8},recipeFingerprint:candidate.recipeFingerprint}),{code:'REVISION_CONFLICT'});
  const corrupt=candidate.geometryBytes.slice();corrupt[0]^=1;assert.throws(()=>installCompiledCandidate(doc,{manifest:candidate.manifest,bytes:corrupt,context,recipeFingerprint:candidate.recipeFingerprint}),{code:'ARTIFACT_CORRUPT'});
  edited=new CadKernel(oc);const changed={...reopened,features:reopened.features.map(f=>f.id==='source'?{...f,params:{...f.params,width:11}}:f)};const rebuilt=await edited.rebuild(changed);assert.deepEqual(rebuilt.compiledInvalidated,['shift']);assert.equal(rebuilt.bodies[0].volume,264);
  await fs.writeFile(path.join(data,'acceptance.json'),JSON.stringify({status:'passed',scope:'native translation original-recipe install and offline v3 reopen',jobId:candidate.manifest.jobId,inputFingerprint:candidate.manifest.inputFingerprint,artifactSha256:candidate.manifest.geometryArtifact.sha256,originalFeatureId:'shift',offlineReopen:true,subsequentLocalOperation:true,upstreamInvalidation:true,staleRejected:true,corruptionRejected:true},null,2));
 }finally{await stop();for(const kernel of [engine,cold,edited])if(kernel)for(const shape of kernel.shapes.values())shape.delete();}
});
