import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import net from 'node:net';
import {spawn} from 'node:child_process';
import {randomBytes} from 'node:crypto';
import init from 'replicad-opencascadejs';
import * as cad from 'replicad';
import {CadKernel} from '../src/cad-kernel.js';
import {createServicesClient} from '../src/services/client.js';
import {compileRemoteFeature} from '../src/services/remote-executor.js';
import {installCompiledCandidate} from '../src/services/geometry-exchange.js';
import {encodeProjectV3,decodeProject} from '../src/project-container.js';
import {prepareReliefSculpt} from '../src/relief-sculpt.js';

test('actual persistent native relief uses geometric intent, retains its original layers and cold-opens offline',async()=>{
 const host=process.env.WEBCAD_SERVICES_TEST_HOST,logo=process.env.WEBCAD_SERVICES_TEST_LOGO_WORKER,worker=process.env.WEBCAD_NATIVE_WORKER,proof=process.env.WEBCAD_NATIVE_ACCEPTANCE,root=process.env.WEBCAD_NATIVE_TEST_ROOT;assert(host&&logo&&worker&&proof&&root,'Actual binaries and kernel proof required');
 await fs.mkdir(root,{recursive:true});const data=await fs.mkdtemp(path.join(root,'relief-')),reserve=net.createServer();await new Promise(r=>reserve.listen(0,'127.0.0.1',r));const port=reserve.address().port;await new Promise(r=>reserve.close(r));const credential=randomBytes(32).toString('hex');
 let child,diagnostic='';const start=()=>{child=spawn(host,['--console'],{windowsHide:true,stdio:['ignore','ignore','pipe'],env:{...process.env,WEBCAD_SERVICES_DATA_ROOT:data,WEBCAD_SERVICES_LOGO_WORKER:logo,WEBCAD_SERVICES_TOKEN:credential,WEBCAD_SERVICES_DEV_HTTP:`http://127.0.0.1:${port}/`,WEBCAD_SERVICES_OCCT_WORKER:worker,WEBCAD_SERVICES_NATIVE_ACCEPTANCE:proof,WEBCAD_SERVICES_PIPE_NAME:'WebCADServices-relief-test'}});child.stderr.on('data',b=>{diagnostic=(diagnostic+b).slice(-4096);});};start();const stop=async()=>{if(child.exitCode===null&&child.signalCode===null){child.kill();await new Promise(r=>child.once('exit',r));}};
 const client=createServicesClient({config:{url:`http://127.0.0.1:${port}/api.ashx`,enabled:true},credential}),kernels=[];let installed;
 try{
  const started=Date.now();for(;;){try{await client.capabilities();break;}catch(e){if(child.exitCode!==null)throw Error(diagnostic);if(Date.now()-started>15000)throw e;await new Promise(r=>setTimeout(r,100));}}
  const oc=await init({wasmBinary:await fs.readFile(new URL('../node_modules/replicad-opencascadejs/dist/replicad_single.wasm',import.meta.url))}),engine=new CadKernel(oc);kernels.push(engine);
  const rectangle=(a,b,c,d)=>[[a,b],[c,b],[c,d],[a,d]],holes=[rectangle(-.28,-.1,-.16,.1)],params={faceId:0,point:[0,0,0],widthMm:6,heightMm:6,depthMm:.8,baseMm:.005,curveToleranceMm:.005,curvePolicy:'preserveTopology',compileLayers:'groupCompatible',layers:[{name:'support left',heightMm:.3,regions:[{outer:rectangle(-.4,-.4,0,.4),holes}]},{name:'support right',heightMm:.3,regions:[{outer:rectangle(.1,-.4,.4,.4)}]},{name:'detail',heightMm:.8,startHeightMm:.29,regions:[{outer:rectangle(-.35,-.3,-.05,.3),holes}]}]},context={documentId:'relief-service-test',documentInstanceId:'relief-service-instance',expectedRevision:3},base=[{id:'cylinder',op:'cylinder',params:{radius:20,height:10},refs:[]},{id:'source',op:'transform',params:{rx:-90,y:-5,z:-20},refs:['cylinder']}];
  const receipts=[];
  for(const maskStrategy of ['cutHoleSolids','faceWithHolesExtrude']){
   const doc={version:2,documentId:context.documentId,imports:{},features:[...base,{id:'relief',op:'relief',params:{...params,maskStrategy},refs:['source']}]};const local=await engine.rebuild({...doc,features:base}),source=engine.serializeFeatureShape('source').data,plan=engine.prepareReliefPlan('source',doc.features.at(-1).params).plan;
   const candidate=await compileRemoteFeature(doc,'relief',source,context,{allowUpload:true,client,plan});assert.equal(candidate.manifest.topologyBinding.kind,'outer-cylinder-geometric-intent');assert.equal(candidate.manifest.strategy,maskStrategy);assert.equal(candidate.manifest.stages.length,2);
   assert.deepEqual(candidate.manifest.stages[0].memberLayerIds,['layer-0','layer-1']);assert.equal(doc.features.at(-1).params.layers.length,3);
   installed=installCompiledCandidate(doc,{manifest:candidate.manifest,bytes:candidate.geometryBytes,context,recipeFingerprint:candidate.recipeFingerprint});assert.deepEqual(installed.features.at(-1).params,doc.features.at(-1).params);assert.deepEqual(installed.features.at(-1).refs,['source']);const built=await engine.rebuild(installed);assert.deepEqual(built.compiledReuse,['relief']);assert(built.bodies[0].solidCount===1&&built.bodies[0].volume>local.bodies[0].volume);
   receipts.push({strategy:maskStrategy,jobId:candidate.manifest.jobId,volumeMm3:built.bodies[0].volume,topologyBinding:candidate.manifest.topologyBinding});
   if(maskStrategy==='faceWithHolesExtrude'){
    await stop();start();const began=Date.now();for(;;){try{await client.capabilities();break;}catch(error){if(child.exitCode!==null||Date.now()-began>15000)throw error;await new Promise(r=>setTimeout(r,100));}}
    const edited={...doc,features:doc.features.map(f=>f.id==='relief'?{...f,params:{...f.params,layers:f.params.layers.map((l,i)=>i===2?{...l,heightMm:.9}:l)}}:f)};
    const editedPlan=engine.prepareReliefPlan('source',edited.features.at(-1).params).plan;
    const changed=await compileRemoteFeature(edited,'relief',source,context,{allowUpload:true,client,plan:editedPlan});
    assert.equal(changed.manifest.stages[0].cacheHit,true,'Unchanged exact support prefix survives Host restart');assert.equal(changed.manifest.stages[1].cacheHit,false,'Edited crest must recalculate');
    assert.notEqual(changed.manifest.jobId,candidate.manifest.jobId);const reference=await engine.rebuild({...edited,features:base});const cachedDoc=installCompiledCandidate(edited,{manifest:changed.manifest,bytes:changed.geometryBytes,context,recipeFingerprint:changed.recipeFingerprint}),cachedBody=await engine.rebuild(cachedDoc);assert(cachedBody.bodies[0].solidCount===1&&cachedBody.bodies[0].volume>reference.bodies[0].volume);
    const altered={...edited,features:edited.features.map(f=>f.id==='relief'?{...f,params:{...f.params,layers:f.params.layers.map((l,i)=>i===0||i===1?{...l,heightMm:.31}:l)}}:f)},alteredPlan=engine.prepareReliefPlan('source',altered.features.at(-1).params).plan;
    const invalidated=await compileRemoteFeature(altered,'relief',source,context,{allowUpload:true,client,plan:alteredPlan});assert(invalidated.manifest.stages.every(stage=>!stage.cacheHit),'Bottom change invalidates every dependent prefix');
    receipts.push({stage:'durable-prefix',hostRestart:true,upperEditCacheHits:changed.manifest.stages.map(s=>s.cacheHit),bottomChangeCacheHits:invalidated.manifest.stages.map(s=>s.cacheHit)});
   }
  }
  for(const mode of ['raise','lower']){
   const originalParams={...params,layers:[{name:'uniform editable support',heightMm:.5,regions:[{outer:rectangle(-.4,-.4,.4,.4),holes}]}],maskStrategy:'faceWithHolesExtrude'},patch={id:'local-detail',domainMm:[-.5,-.5,.5,.5],samples:17,protectionMm:.03};
   const patched=prepareReliefSculpt(originalParams,[{mode,radiusMm:.15,amountMm:.1,points:[[0,0]]}],{layerIndex:0,patch}),doc={version:2,documentId:context.documentId,imports:{},features:[...base,{id:'relief',op:'relief',params:{...originalParams,...patched.params},refs:['source']}]},local=await engine.rebuild({...doc,features:base}),source=engine.serializeFeatureShape('source').data,plan=engine.prepareReliefPlan('source',doc.features.at(-1).params).plan;
   assert.equal(plan.semanticVersion,'relief.compiled-contours-local-patch-1.1');const candidate=await compileRemoteFeature(doc,'relief',source,context,{allowUpload:true,client,plan});installed=installCompiledCandidate(doc,{manifest:candidate.manifest,bytes:candidate.geometryBytes,context,recipeFingerprint:candidate.recipeFingerprint});const accepted=await engine.rebuild(installed);assert(accepted.bodies[0].solidCount===1&&accepted.bodies[0].volume>local.bodies[0].volume,JSON.stringify({mode,local:local.bodies[0].volume,native:accepted.bodies[0].volume,nativeReported:candidate.manifest.validation.volumeMm3}));assert.equal(installed.features.at(-1).params.layers[0].localPatches[0].id,'local-detail');receipts.push({stage:'independent-local-patch',mode,volumeMm3:accepted.bodies[0].volume,artifact:candidate.manifest.geometryArtifact.sha256});
  }
  let strokeInstalled;
  if((await client.capabilities()).operations.some(c=>c.semanticVersion==='relief.compiled-contours-strokes-1.2')){
   const strokeParams={faceId:0,point:[0,0,0],widthMm:6,heightMm:6,depthMm:.3,baseMm:.005,curveToleranceMm:.005,curvePolicy:'preserveTopology',maskStrategy:'faceWithHolesExtrude',layers:[{name:'deep source stroke',heightMm:.3,mode:'engrave',strokes:[{points:[[-.2,0],[.2,0]],widthMm:.12}]},{name:'shallow branch',heightMm:.18,mode:'engrave',strokes:[{points:[[0,-.2],[0,.2]],widthMm:.12},{points:[[0,0],[.1,.1]],widthMm:.12}]}]},doc={version:2,documentId:context.documentId,imports:{},features:[...base,{id:'relief',op:'relief',params:strokeParams,refs:['source']}]},local=await engine.rebuild({...doc,features:base}),source=engine.serializeFeatureShape('source').data,plan=engine.prepareReliefPlan('source',strokeParams).plan,candidate=await compileRemoteFeature(doc,'relief',source,context,{allowUpload:true,client,plan});
   assert.equal(plan.semanticVersion,'relief.compiled-contours-strokes-1.2');assert.deepEqual(plan.layers.map(l=>l.mode),['engrave','engrave']);strokeInstalled=installCompiledCandidate(doc,{manifest:candidate.manifest,bytes:candidate.geometryBytes,context,recipeFingerprint:candidate.recipeFingerprint});const built=await engine.rebuild(strokeInstalled);assert.deepEqual(strokeInstalled.features.at(-1).params,strokeParams);assert.equal(built.bodies[0].solidCount,1);assert(built.bodies[0].volume<local.bodies[0].volume);const nativeShape=engine.shapes.get('relief'),solids=[nativeShape.solids],queries=solids.map(s=>new cad.DistanceQuery(s[0])),support=plan.layers[0].support,R=support.radiusMm,n=support.normal,a=support.axis,t=[a[1]*n[2]-a[2]*n[1],a[2]*n[0]-a[0]*n[2],a[0]*n[1]-a[1]*n[0]],center=support.origin.map((v,i)=>v-R*n[i]),materialSamples=[];
   try{for(const [x,y,heightMm,expected] of [[.6,0,-.1,false],[.6,0,-.25,false],[.6,0,-.32,true],[0,.6,-.1,false],[0,.6,-.2,true],[0,.6,-.32,true],[.9,.9,-.1,true]]){const world=center.map((v,i)=>v+a[i]*y+(R+heightMm)*(n[i]*Math.cos(x/R)+t[i]*Math.sin(x/R))),material=queries.map(q=>{const p=cad.makeVertex(world);try{return q.distanceTo(p)<1e-7;}finally{p.delete();}});assert.equal(material[0],expected,JSON.stringify({stage:'local-depth-material',x,y,heightMm,expected,material}));assert.deepEqual(material,[expected],'Native exact depth/material');materialSamples.push({xMm:x,yMm:y,heightMm,material:expected});}}finally{queries.forEach(q=>q.delete());solids.flat().forEach(s=>s.delete());}
   receipts.push({stage:'open-strokes-distinct-engraving-depths',sourceVolumeMm3:local.bodies[0].volume,nativeVolumeMm3:built.bodies[0].volume,sourceLayerDepths:strokeParams.layers.map(l=>l.heightMm),materialSamples,jobId:candidate.manifest.jobId});
  }
  const bytes=encodeProjectV3(installed);await fs.writeFile(path.join(data,'relief.webcad'),bytes);await stop();const cold=new CadKernel(oc);kernels.push(cold);const original=cold.operation.bind(cold);cold.operation=(f,...args)=>{if(f.id==='relief')throw Error('Saved native relief must not recalculate');return original(f,...args);};const opened=await cold.rebuild(await decodeProject(bytes));assert.deepEqual(opened.compiledReuse,['relief']);assert.equal(opened.bodies[0].solidCount,1);assert.equal(installed.features.at(-1).params.layers[0].localPatches[0].deltaMm.length,17);
  if(strokeInstalled){const reopened=await cold.rebuild(await decodeProject(encodeProjectV3(strokeInstalled)));assert.deepEqual(reopened.compiledReuse,['relief']);assert.deepEqual(strokeInstalled.features.at(-1).params.layers.map(l=>l.heightMm),[.3,.18]);}
  await fs.writeFile(path.join(data,'acceptance.json'),JSON.stringify({status:'passed',scope:'small persistent native relief and offline original-layer installation; not a real-product acceptance',receipts,offline:true},null,2));
 }finally{await stop();for(const kernel of kernels)for(const shape of kernel.shapes.values())try{shape.delete();}catch{}}
});
