import test from 'node:test';
import assert from 'node:assert/strict';
import {connectVector,convertVectorEntities,parseDxf,curveData,sourceSplineDescriptor} from '../src/vector-import.js';
const line=(id,a,b)=>({id,type:'line',startMm:a,endMm:b});
test('source splines preserve parameters separately from fit point evidence',()=>{
 const fit={type:'SPLINE',handle:'A1',degree:3,fit_pts:[[0,0,0],[1,2,0],[3,0,0]],fit_tol:.001,beg_tan_vec:[1,0,0],end_tan_vec:[1,-1,0]},original=structuredClone(fit);
 const converted=convertVectorEntities([fit],{scaleMm:2});assert.equal(converted.entities.length,0);const descriptor=converted.unsupported[0].sourceSpline;assert.equal(descriptor.representation,'fit-points');assert.equal(descriptor.geometryCreated,false);assert.equal(descriptor.fitToleranceMm,.002);assert.deepEqual(descriptor.fitPoints[1],[2,4,0]);assert.deepEqual(fit,original);
 const nurbs=sourceSplineDescriptor({degree:2,controlPoints:[[0,0],[1,2],[3,0]],knots:[0,0,0,1,1,1],weights:[1,2,1],periodic:false});assert.equal(nurbs.representation,'nurbs-parameters');assert.deepEqual(nurbs.weights,[1,2,1]);assert.equal(nurbs.periodic,false);
 assert.equal(descriptor.periodic,null);const dxf=['0','SECTION','2','ENTITIES','0','SPLINE','5','B2','70','0','71','2','40','0','40','0','40','0','40','1','40','1','40','1','10','0','20','0','10','1','20','2','10','3','20','0','0','ENDSEC','0','EOF'].join('\n');const parsed=convertVectorEntities(parseDxf(dxf)).unsupported[0].sourceSpline;assert.equal(parsed.representation,'nurbs-parameters');assert.deepEqual(parsed.controlPoints,[[0,0,0],[1,2,0],[3,0,0]]);assert.deepEqual(parsed.knots,[0,0,0,1,1,1]);
});
const square=()=>[line('a',[0,0],[4,0]),line('b',[4,0],[4,3]),line('c',[4,3],[0,3]),line('d',[0,3],[0,0])];
test('unordered and reversed lines close without altering source',()=>{const e=square();[e[1].startMm,e[1].endMm]=[e[1].endMm,e[1].startMm];e.reverse();const original=JSON.stringify(e),r=connectVector({entities:e});assert.equal(r.canCreateFace,true);assert.equal(r.profile.loops.length,1);assert.deepEqual(r.receipt.bounds,[0,0,4,3]);assert.equal(JSON.stringify(e),original);});
test('gaps obey explicit tolerance; movement is reported',()=>{const e=square();e[0].startMm=[0.001,0];assert.equal(connectVector({entities:e}).canCreateFace,false);const r=connectVector({entities:e,toleranceMm:0.002});assert.equal(r.canCreateFace,true);assert.equal(r.receipt.moves[0].endpointMoveMm,0.0005);});
test('branch, duplicate and crossing boundaries are rejected',()=>{assert.equal(connectVector({entities:[...square(),line('extra',[0,0],[1,1])]}).canCreateFace,false);assert.equal(connectVector({entities:[...square(),line('extra',[0,0],[4,0])]}).canCreateFace,false);const p=[[0,0],[4,3],[0,3],[4,0]];assert.equal(connectVector({entities:p.map((a,i)=>line(`e${i}`,a,p[(i+1)%4]))}).canCreateFace,false);});
test('nested circles create hole and island regions',()=>{const r=connectVector({entities:[10,6,2].map((d,i)=>({id:`c${i}`,type:'circle',centerMm:[0,0],diameterMm:d}))});assert.equal(r.canCreateFace,true);assert.equal(r.profile.regions.length,2);assert.equal(r.profile.regions[0].holeLoopIds.length,1);});
test('analytic semicircle and line preserve radius through orientation',()=>{const r=connectVector({entities:[{id:'arc',type:'arc3',startMm:[0,0],midMm:[1,-1],endMm:[2,0]},line('top',[2,0],[0,0])],origin:[1,0],flipY:true});assert.equal(r.canCreateFace,true);assert.equal(curveData(r.profile.entities[0]).r,1);r.receipt.bounds.forEach((v,i)=>assert.ok(Math.abs(v-[-1,0,1,1][i])<1e-9));});
test('DXF excludes block definitions and paper space, keeps analytic bulge',()=>{const dxf=['0','SECTION','2','BLOCKS','0','CIRCLE','10','99','20','99','40','8','0','ENDSEC','0','SECTION','2','ENTITIES','0','LWPOLYLINE','5','ABC','8','PRODUCT','70','1','10','0','20','0','42','1','10','2','20','0','0','CIRCLE','67','1','10','0','20','0','40','2','0','ENDSEC','0','EOF'].join('\n');const r=convertVectorEntities(parseDxf(dxf));assert.equal(r.entities.length,2);assert.equal(r.entities[0].type,'arc3');assert.equal(r.entities[0].sourceId,'ABC');assert.equal(curveData(r.entities[0]).r,1);assert.equal(connectVector(r).canCreateFace,true);});
test('unsupported spline and nonplanar lines are explicitly reported',()=>{const r=convertVectorEntities([{type:'SPLINE',handle:'1'},{type:'LINE',startPoint:{x:0,y:0,z:1},endPoint:{x:1,y:0,z:1}}]);assert.equal(r.entities.length,0);assert.equal(r.unsupported.length,2);});
test('reject invalid IDs and excess tolerance',()=>{assert.throws(()=>connectVector({entities:[line('bad id',[0,0],[1,0])]}));assert.throws(()=>connectVector({entities:square(),toleranceMm:2}));});
