import {DISPLAY_DEFAULTS,DISPLAY_PRESETS,DISPLAY_RANGES} from './display-preferences.js';
import {METAL_FINISHES} from '../../metal-materials.js';
import {getLogoConverterConfig,setLogoConverterConfig} from '../../logo-converter-settings.js';
export function showDisplaySettings({openDialog,element,button,state,emit,api,closeDialog,finishSelect,finishControl}){
  const d=openDialog('全局显示设置','适用于当前浏览器，保存到 Cookie 并在下次打开时载入。单个实体的显式颜色、材质优先于全局默认。灯光角度绕世界 Z 轴，俯仰从 XY 平面起算。');
  d.style.width='min(780px,92vw)';
  const form=element('form',{class:'parameter-form'}),controls={};form.style.gridTemplateColumns='repeat(auto-fit,minmax(180px,1fr))';
  const fields=[['defaultColor','默认设计颜色','color'],['defaultFinish','默认材质','finish'],['background','背景颜色','color'],['environmentMode','反射环境','environment'],['lightAzimuth','主光方位（°）'],['lightElevation','主光俯仰（°）'],['keyIntensity','主光亮度'],['fillIntensity','补光亮度'],['ambientIntensity','环境漫射亮度'],['environmentRotation','反射环境旋转（°）'],['environmentIntensity','反射强度'],['roughnessOffset','金属柔和度（粗糙度增量）'],['exposure','金属曝光']];
  for(const [key,title,type]of fields){const label=element('label',{class:'form-field'});label.append(element('span',{},title));let input;if(type==='environment'){input=element('select',{'aria-label':title});for(const [value,title]of [['studio','均匀工作室'],['hdr','原 HDR 工作室']])input.append(element('option',{value},title));}else if(type==='finish'){input=element('select',{'aria-label':title});for(const [value,preset]of Object.entries(METAL_FINISHES))input.append(element('option',{value},preset.label));}else {input=element('input',{type:type||'number','aria-label':title,required:''});if(DISPLAY_RANGES[key]){input.min=DISPLAY_RANGES[key][0];input.max=DISPLAY_RANGES[key][1];input.step='any';}}input.value=(state.displayPreferences||DISPLAY_DEFAULTS)[key];controls[key]=input;label.append(input);form.append(label);}
  const presets=element('div',{class:'dialog-footer wide'});for(const [key,title]of [['studio','标准工作室'],['soft','柔和金属'],['contrast','明暗对比']])presets.append(button(title,()=>{for(const [k,v]of Object.entries(DISPLAY_PRESETS[key]))controls[k].value=v;},'secondary'));form.prepend(presets);
  const note=element('p',{class:'property-footnote wide'},'预设会填写整组默认值；点击应用后显示并保存。实体自身的颜色和材质在右侧属性修改。'),error=element('p',{class:'form-error wide',role:'alert'});form.append(note,error);
  const foot=element('div',{class:'dialog-footer wide'}),apply=element('button',{type:'submit',class:'primary'},'应用并记住');foot.append(button('恢复默认',()=>{for(const [k,v]of Object.entries(DISPLAY_DEFAULTS))controls[k].value=v;},'secondary'),apply,button('关闭',closeDialog,'secondary'));form.append(foot);
  form.addEventListener('submit',async e=>{e.preventDefault();if(!form.reportValidity())return;apply.disabled=true;error.textContent='';try{const values=Object.fromEntries(fields.map(([k,,type])=>[k,type?controls[k].value:Number(controls[k].value)]));const result=await emit('displayPreferences',values);if(result===false)return;note.textContent=result.persisted?'已应用并记住，下次自动载入。':'';if(!result.persisted)api.showWarning('设置已应用，但浏览器未允许保存 Cookie；下次打开可能恢复默认。');}catch(ex){api.showError(ex.message);error.textContent='';}finally{apply.disabled=false;}});
  d.append(form);finishSelect.value=state.document?.renderFinish||'';d.append(finishControl);
  const converter=element('section',{class:'logo-converter-settings'}),urlLabel=element('label',{class:'form-field'},'LOGO 格式转换 URL（含 userid）'),urlInput=element('input',{type:'url','aria-label':'LOGO 格式转换 URL'}),keyLabel=element('label',{class:'form-field'},'转换 Key（留空保持原值）'),keyInput=element('input',{type:'password',autocomplete:'new-password','aria-label':'LOGO 转换 Key'}),save=button('保存转换配置',()=>{save.disabled=true;try{setLogoConverterConfig({url:urlInput.value.trim(),key:keyInput.value});keyInput.value='';converterStatus.textContent='已保存到当前浏览器；重新打开后会自动载入。';}catch(error){converterStatus.textContent=error.message;}finally{save.disabled=false;}},'secondary'),converterStatus=element('p',{class:'property-footnote'},'');
  urlLabel.append(urlInput);keyLabel.append(keyInput);converter.append(element('h3',{},'LOGO 格式转换'),urlLabel,keyLabel,save,converterStatus);d.append(converter);
  try{const data=getLogoConverterConfig();urlInput.value=data.url;converterStatus.textContent=data.configured?'当前浏览器已保存 URL 和 Key。':'尚未保存转换配置。';}catch(error){converterStatus.textContent=error.message;}
 }
