// UI translations are local; no remote translation or network request is used.
let language = 'zh';
try { language = localStorage.getItem('webcad.language') === 'en' ? 'en' : 'zh'; } catch {}
const dictionary = {
 '多位置打孔':'Multi-position holes','钻孔起点列表':'Drill start positions','每行一组 X,Y,Z，共 1 至 100 个钻孔起点':'One X,Y,Z start position per line; 1 to 100 holes','请输入 1 至 100 个有效的 X,Y,Z 钻孔起点。':'Enter 1 to 100 valid X,Y,Z drill start positions.','每个坐标是钻孔刀具的全局起点。所有孔沿指定轴方向切入；每个孔都必须实际去除材料，不生成螺纹。':'Each position is a global drill-tool start. Holes follow the shared axis and direction; every hole must remove material. No threads are generated.','8. 快捷模型新增扁平框和安装板；尺寸按模板字段定义，安装板孔由参数生成。':'8. Quick models include a flat frame and mounting plate. Dimensions follow the template fields; plate holes are parameter driven.','9. 多位置打孔：先选择实体，再输入 1 至 100 个全局钻孔起点；共享孔半径、深度及轴向，不生成螺纹。':'9. Multi-position holes: select a body and enter 1 to 100 global drill starts. Radius, depth and axis are shared; threads are not generated.',
 '高级':'Advanced','设计原色':'Design colors','浅金':'Light gold','亮镍':'Bright nickel','24K 金':'24K gold','哑镍':'Matte nickel','哑浅金':'Matte light gold','哑 24K 金':'Matte 24K gold','哑枪色':'Matte gunmetal','仿古黄铜':'Antique brass','仿古银':'Antique silver','折线轮廓':'Polyline profile','选择预设轮廓或交互绘制。水平/垂直吸附是绘制辅助，不是完整约束求解器。':'Choose an exact preset or draw interactively. Horizontal/vertical snapping is a drawing aid, not a full constraint solver.',
 '同心圆恒截面单圈；开缝为底部正中平行平切。':'Constant-section circular ring; the optional bottom-center gap has parallel cut faces.','半圆冠、两直腿、底部圆弯；内高量到下横杠上沿。':'Semicircular crown, straight legs and rounded bottom. Inner height is measured to the top of the bottom bar.','圆角方线 U 主体与固定圆杆融合；杆底与脚底齐平。':'Rounded-square U frame fused with a round bar; bar bottom aligns with the leg bottoms.','恒截面圆角矩形框；内宽高至少为截面尺寸的 4 倍。':'Constant-section rounded rectangular frame. Inner width and height must be at least four times the section size.','外框整体内高；固定圆杆偏移上正下负，不支持开缝。':'Height is the full frame opening. Bar offset is positive upward; gaps are not supported.','四段相切圆弧，不是椭圆或跑道圈；缝在右端正中。':'Four tangent circular arcs, not an ellipse or stadium. Optional gap is centered on the right end.','平面环片，外径 = 内径 + 2 × 径向宽度；无额外倒角。':'Flat annulus: outer diameter = inner diameter + 2 × radial width. No additional chamfers.',
 '精确实体设计':'Solid modeling','本机计算 · 毫米':'Local · mm','工具类别':'Tool categories','建模工具':'Modeling tools','设计树':'Design tree','实体':'Body','Ctrl 多选':'Ctrl: multi-select','建模历史':'Feature history','工程保存为 .webcad':'Save as .webcad','可保留参数与完整建模历史':'Keep parameters and feature history','选择模式':'Selection mode','从一个形状开始':'Start with a shape','创建精确实体，或打开 STEP 文件继续加工。':'Create a precise solid, or open STEP to continue modeling.','拖入文件以打开 · 单位 mm':'Drop a file to open · mm','左键选择 · 拖动旋转 · 滚轮缩放 · 右键平移':'Click to select · Drag to orbit · Scroll to zoom · Right drag to pan','透视视图':'Perspective','正交视图':'Orthographic','正在计算实体…':'Computing solids…','属性':'Properties','正在初始化建模内核…':'Initializing CAD kernel…','内核加载中':'Kernel loading','内核就绪':'Kernel ready','新建工程':'New project',
 '新建':'New','打开':'Open','保存工程':'Save project','导出':'Export','示例':'Examples','帮助':'Help','重命名工程':'Rename project','取消':'Cancel','保存':'Save','确定':'Create','关闭':'Close','知道了':'OK','名称':'Name','应用参数':'Apply parameters','预览':'Preview','应用预览':'Apply preview','放弃预览':'Cancel preview','预览已生成，可调整参数重新预览或应用。':'Preview ready. Adjust parameters and preview again, or apply.','请先预览当前参数。':'Preview the current parameters first.',
 '建模':'Model','编辑':'Edit','视图':'View','基本实体':'Primitives','轮廓成型':'Profiles','实体运算':'Boolean','修饰':'Modify','变换与复制':'Transform','阵列':'Patterns','管理':'Manage','高级建模':'Advanced','快捷模型':'Quick models','面加工':'Face tools','辅助':'Assist',
 '长方体':'Box','圆柱':'Cylinder','球体':'Sphere','圆锥':'Cone','圆环':'Torus','拉伸':'Extrude','旋转成型':'Revolve','移动 / 旋转':'Transform','复制':'Copy','镜像':'Mirror','合并':'Union','相减':'Subtract','相交':'Intersect','圆角':'Fillet','倒角':'Chamfer','抽壳':'Shell','打孔':'Hole','直线阵列':'Linear pattern','环形阵列':'Circular pattern','删除':'Delete','导入':'Import','绘制草图':'Sketch','扫掠':'Sweep','放样':'Loft','分割':'Split','提取实体':'Extract solid','面上打孔':'Face hole','面上拉伸':'Face extrusion','剖切':'Section',
 '宽度':'Width','深度':'Depth','高度':'Height','半径':'Radius','底部半径':'Base radius','顶部半径':'Top radius','主半径':'Major radius','管半径':'Tube radius','孔半径':'Hole radius','孔深':'Hole depth','起点 X':'Start X','起点 Y':'Start Y','起点 Z':'Start Z','钻孔轴':'Drill axis','钻孔方向':'Drill direction','轴正方向':'Positive axis','轴负方向':'Negative axis','数量（包含原件）':'Count (including original)','每步 X 位移':'X spacing','每步 Y 位移':'Y spacing','每步 Z 位移':'Z spacing','分布角度':'Distribution angle','旋转轴方向':'Axis direction','轴心 X':'Center X','轴心 Y':'Center Y','轴心 Z':'Center Z','轮廓':'Profile','草图平面':'Sketch plane','轮廓宽度':'Profile width','轮廓深度':'Profile depth','轮廓半径':'Profile radius','多边形顶点':'Polygon vertices','拉伸高度（负数反向）':'Extrusion height (signed)','距旋转轴':'Radial offset','旋转角度':'Revolution angle','X 位移':'X translation','Y 位移':'Y translation','Z 位移':'Z translation','绕 X 轴旋转':'X rotation','绕 Y 轴旋转':'Y rotation','绕 Z 轴旋转':'Z rotation','等比缩放':'Uniform scale','镜像平面':'Mirror plane','圆角半径':'Fillet radius','倒角距离':'Chamfer distance','壁厚':'Wall thickness','矩形':'Rectangle','圆形':'Circle','多边形':'Polygon','圆角矩形':'Rounded rectangle','圆弧':'Arc','线段':'Line','每行一组 X,Y，至少三个顶点':'One X,Y pair per line; at least 3 vertices','每行一组 X,Y,Z，至少两个点':'One X,Y,Z point per line; at least 2 points','外轮廓圆角':'Outer corner radius','启用':'Enabled','关闭辅助':'Off','正向':'Positive','反向':'Negative','轴方向':'Axis','平面位置':'Plane position','实体索引（从 0 开始）':'Solid index (zero-based)','起始角':'Start angle','结束角':'End angle','封闭方式':'Closure','扇形':'Sector','弓形':'Segment','水平 / 垂直吸附':'Horizontal / vertical snap','网格吸附':'Grid snap','绘制方式':'Sketch mode','预设轮廓':'Preset profile','交互多边形':'Interactive polygon','草图辅助':'Sketch assists','折线路径':'Polyline path','首截面尺寸':'Start profile size','末截面尺寸':'End profile size','截面距离':'Section distance','圆截面半径':'Circular profile radius','新增实体':'New body','合并到实体':'Add to body','切除实体':'Cut from body','加工方式':'Operation','圆弧不能代表完整约束草图。':'Arc presets are not a full constraint solver.',
 '等轴':'Isometric','前视':'Front','后视':'Back','俯视':'Top','仰视':'Bottom','左视':'Left','右视':'Right','实体 + 边线':'Shaded edges','线框':'Wireframe','透视':'Perspective','正交':'Orthographic','适合窗口':'Fit','⌂ 适合窗口':'⌂ Fit','网格开关':'Grid','测量':'Measure','截图':'Screenshot','面':'Face','边':'Edge','↶ 撤销':'↶ Undo','↷ 重做':'↷ Redo','＋ 创建长方体':'+ Create box','打开模型':'Open model','移动手柄':'Move gizmo','旋转手柄':'Rotate gizmo','关闭手柄':'Hide gizmo','吸附':'Snap','选中材质':'Selected material','应用到选中':'Apply to selected','渲染':'Finish','金属渲染':'Metal finish','全场景表面预览，选择后保持到下次打开':'Scene appearance; remembered for next session',
 '显示实体':'Show body','隐藏实体':'Hide body','尚无实体':'No bodies yet','创建操作后显示历史':'Your features appear here','编辑此步骤的参数':'Edit this feature','选择一个实体':'Select a body','查看尺寸与体积，修改参数或进行实体加工。':'Inspect dimensions and volume; edit parameters or modify the body.','按 Ctrl 多选进行布尔运算':'Ctrl-select bodies for Boolean operations','X 尺寸':'X size','Y 尺寸':'Y size','Z 尺寸':'Z size','体积':'Volume','导入几何保留精确形状。可使用工具栏继续移动、布尔、倒角等加工；不包含原软件特征树。':'Imported geometry preserves precise shapes. Transform and modify it with CAD tools; source feature history is not recovered.','操作未完成':'Operation failed','删除选中实体':'Delete selected bodies','此操作保留在建模历史中，可以撤销。':'This operation remains in feature history and can be undone.','删除实体':'Delete bodies',
 '导出模型':'Export model','选择交换格式。若要继续修改参数，请同时保存 WebCAD 工程。':'Choose an exchange format. Save a WebCAD project to retain editable parameters.','精确实体 · 用于 Creo、SolidWorks、Fusion 等 CAD':'Precise solids · Creo, SolidWorks, Fusion and other CAD tools','三角网格 · 用于切片与 3D 打印，不保留精确曲面':'Triangle mesh · slicing and 3D printing; no precise surfaces','OpenCascade 原生精确几何':'OpenCascade native precise geometry','导出文件':'Export file','WebCAD 使用指南':'WebCAD guide','原只读查看器（DWG / STL / IGES）':'Original read-only viewer (DWG / STL / IGES)','在独立页面查看原有文件；只读查看不代表可以在 WebCAD 中编辑二维图纸或网格。':'View existing files in a separate tab. Read-only viewing does not imply 2D or mesh editing in WebCAD.','打开示例工程':'Open an example','选择一个可编辑的实体工程，查看建模历史并修改尺寸。':'Open an editable project to explore its history and change dimensions.','带孔安装支架':'Mounting bracket','板件、安装孔与支撑结构':'Plates, mounting holes and support','圆角扣框':'Rounded buckle frame','扣框轮廓与圆角加工':'Buckle profile and fillets','薄壁盒':'Thin-wall box','盒体与壁厚设计':'Box geometry and wall thickness',
 '输入尺寸，创建可编辑的精确实体。':'Enter dimensions to create an editable precise solid.','从全局 X、Y、Z 起点沿指定轴方向钻孔，孔深单位 mm。钻孔圆柱必须与选中实体相交。':'Drill from global X,Y,Z along the selected axis. Depth is in mm; the drilling cylinder must intersect the body.','沿每步位移复制选中实体。数量包含原件；阵列作为一个复合实体保存。':'Copy by the specified spacing. Count includes the source; the result is one compound body.','围绕指定轴心复制实体。数量包含原件；360° 均匀环绕，部分角度包含起点与终点；结果作为一个复合实体保存。':'Pattern around the axis. Count includes the source. 360° is evenly spaced; partial angles include both endpoints. Output is a compound.','对选中的实体进行变换。位移单位 mm，旋转单位 °。':'Transform the selected body. Translation: mm; rotation: degrees.','保留原实体，并创建变换后的副本。':'Keep the source and create a transformed copy.','沿全局坐标平面镜像，保留原实体。':'Mirror about a global plane and keep the source.','已选边时仅处理选中边；否则处理实体的全部边。半径过大可能无法生成。':'Use selected edges, or all edges if none are selected. Large radii may fail.','已选边时仅处理选中边；否则处理实体的全部边。':'Use selected edges, or all edges if none are selected.','先切换到“面”，选择需要移除的面，再设定壁厚。':'Switch to Face selection, select the faces to remove, then set wall thickness.','选择预设轮廓或填写多边形顶点，也可以使用“绘制草图”。':'Choose a profile or enter polygon vertices, or use Sketch.','XY 平面轮廓绕全局 Y 轴旋转；XZ / YZ 平面轮廓绕全局 Z 轴旋转。距旋转轴为轮廓沿平面水平方向的偏移。':'XY profiles revolve about global Y; XZ/YZ profiles about global Z. Radial offset follows the horizontal profile axis.','依选择顺序：第一个实体减去其余实体':'Selection order: subtract subsequent bodies from the first','选择一个实体及需要移除的面':'Select a body and the faces to remove','在视图中绘制 XY 平面轮廓':'Draw an XY profile in the viewport','按 Ctrl 依次选择至少两个实体':'Ctrl-select at least two bodies in order','；从第一个减去后选实体':'; subtract later bodies from the first',
 '多边形请输入至少三个有效的 X,Y 顶点。':'Enter at least three valid X,Y vertices.','请填写有效数值。':'Enter a valid number.','阵列数量必须为 2 至 100 的整数。':'Pattern count must be an integer between 2 and 100.','拉伸高度不能为 0；负数表示反向拉伸。':'Extrusion height cannot be zero; negative values reverse direction.','尺寸必须大于 0。':'The dimension must be greater than zero.','该尺寸不能为负数。':'The dimension cannot be negative.','旋转角度应大于 0 且不超过 360°。':'Angle must be greater than 0 and at most 360°.','管半径必须小于主半径。':'Tube radius must be smaller than major radius.','圆锥至少一个半径应大于 0。':'At least one cone radius must be positive.','数量必须是非负整数。':'Enter a nonnegative integer.','路径至少需要两个有效的 X,Y,Z 点。':'The path needs at least two valid X,Y,Z points.',
 '1. 新建：使用工具栏创建实体，或“绘制草图”后拉伸。':'1. Create a primitive from the toolbar, or draw a sketch and extrude it.','2. 编辑：选中实体，在右侧修改生成参数；历史条目也可编辑。':'2. Select a body to edit its parameters on the right, or select a history step.','3. 布尔：按 Ctrl 依次选择两个实体，再合并、相减或相交。相减会从第一个实体减去后选实体。':'3. Ctrl-select bodies in order, then union, subtract or intersect. Subtract removes later selections from the first.','4. 圆角 / 倒角：切换“边”并选择边；不选边时处理全部边。':'4. Fillet / chamfer: select edges in Edge mode, or leave edges unselected to process all.','5. 视图：左键拖动旋转，滚轮缩放，右键拖动平移。':'5. View: left-drag to orbit, scroll to zoom, right-drag to pan.','6. 保存工程可保留参数和导入源文件；STEP 用于 CAD 交换，STL 用于 3D 打印。':'6. Projects retain parameters and imported sources. STEP is for CAD exchange; STL for 3D printing.','7. 导入 STEP 可以继续加工，但不能恢复其他 CAD 软件的原始特征树。':'7. Imported STEP can be modified, but does not recover the original CAD feature history.','所有几何计算在本机浏览器进行。尺寸单位：毫米；角度单位：度。':'Geometry is computed locally in the browser. Length: millimeters; angle: degrees.','MCP 连接':'MCP connection','服务地址':'Service URL','AI 连接状态':'AI connection','修订':'Revision','未连接':'Disconnected','已连接':'Connected','连接中':'Connecting','AI 工具可通过此地址连接本机 WebCAD。':'AI tools can connect to local WebCAD at this endpoint.','这是本机接口地址，不是上传服务。':'This is a local endpoint, not an upload service.',
 '精抛银':'Polished silver','拉丝银':'Brushed silver','哑光银':'Matte silver','亮铬':'Bright chrome','黄金':'Gold','玫瑰金':'Rose gold','古铜':'Antique bronze','枪色':'Gunmetal','黑镍':'Black nickel','塑料预览':'Plastic preview',
};
export function addTranslations(entries) { Object.assign(dictionary, entries); }
export function getLanguage() { return language; }
export function setLanguage(value) { language = value === 'en' ? 'en' : 'zh'; try { localStorage.setItem('webcad.language', language); } catch {} return language; }
export function t(message, params = {}) {
 let text = String(message ?? '');
 if (language === 'en') {
  if (dictionary[text]) text = dictionary[text];
  else text = text.split('\n').map(line => dictionary[line] || line).join('\n');
  if (/[\u3400-\u9fff]/.test(text)) {
   text = text.replace(/^(\d+) 个实体$/, '$1 bodies').replace(/^选中 (\d+) \/ (\d+)$/, 'Selected $1 / $2').replace(/^仅导出选中实体（(\d+)）$/, 'Export selected bodies only ($1)').replace(/^已选择 (\d+) 个实体。相减顺序以选择顺序为准。$/, '$1 bodies selected. Subtraction follows selection order.').replace(/^已选边：/, 'Selected edges: ').replace(/^已选面：/, 'Selected faces: ').replace(/ · 参数$/, ' · Parameters');
   for (const [zh,en] of Object.entries(dictionary).sort((a,b)=>b[0].length-a[0].length)) if (zh.length>=2 && text.includes(zh)) text=text.split(zh).join(en);
  }
 }
 for (const [key,value] of Object.entries(params)) text=text.replaceAll(`{${key}}`,String(value));
 return text;
}
/** Translate chrome without replacing form values, imported names, or viewport labels. */
export function watchTranslations(root) {
 const original=new WeakMap(), attributes=new WeakMap();
 let observer;
 const translate=()=>{
  observer?.disconnect();
  const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);
  let node;
  while((node=walker.nextNode())){
   if(node.parentElement?.closest('#viewport,.tree-name,.property-title,#document-name,textarea,script,style,[data-no-translate]'))continue;
   const prior=original.get(node), current=node.nodeValue;
   const source=prior && current===prior.output ? prior.source:current;
   const leading=source.match(/^\s*/)?.[0]||'', trailing=source.match(/\s*$/)?.[0]||'';
   const output=source.trim()?leading+t(source.trim())+trailing:source;
   original.set(node,{source,output});if(current!==output)node.nodeValue=output;
  }
  for(const el of root.querySelectorAll('[title],[aria-label],[placeholder]')){
   const record=attributes.get(el)||{};
   for(const attr of ['title','aria-label','placeholder'])if(el.hasAttribute(attr)){
    const current=el.getAttribute(attr), previous=record[attr],source=previous&&current===previous.output?previous.source:current,output=t(source);
    record[attr]={source,output};if(current!==output)el.setAttribute(attr,output);
   }
   attributes.set(el,record);
  }
  root.setAttribute('lang',language==='en'?'en':'zh-CN');
  observer?.observe(root,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['title','aria-label','placeholder']});
 };
 observer=new MutationObserver(translate);translate();
 return {translate,destroy:()=>observer.disconnect()};
}
