/** Machine-readable help only; the existing browser/kernel remains the operation authority. */
import { advancedOperations } from './advanced-operation-catalog.js';
import { referenceOperations } from './reference-tool-fields.js';
import { referenceProfileOperations } from './reference-profile-tools.js';
const num=(description,extra={})=>({type:'number',description,...extra});
const length=(description,extra={})=>num(description+' (mm)',extra);
const positive=description=>length(description,{exclusiveMinimum:0});
const integer=(description,minimum=0,maximum)=>({type:'integer',description,minimum,...(maximum===undefined?{}:{maximum})});
const choice=(description,values)=>({type:'string',description,enum:values});
const flag=description=>({type:'boolean',description});
const ids={type:'array',items:integer('Zero-based topology index'),minItems:1};
const point3={type:'array',items:{type:'number'},minItems:3,maxItems:3,description:'World coordinate [x,y,z] in mm'};
const point2={type:'array',items:{type:'number'},minItems:2,maxItems:2,description:'XY coordinate in mm'};
const plane=choice('Global plane',['XY','XZ','YZ']);
const axis=choice('Global axis',['X','Y','Z']);
const angle=num('Degrees',{exclusiveMinimum:0,maximum:360});
const profiles={profile:choice('Closed cross-section',['rectangle','circle','polygon','roundedRectangle','arc']),width:positive('Width'),depth:positive('Depth'),radius:positive('Circle/arc radius'),cornerRadius:positive('Rounded rectangle corner radius; less than half shorter side'),points:{type:'array',minItems:3,maxItems:1000,items:{type:'array',items:{type:'number'},minItems:2,maxItems:2}},startAngle:num('Arc start (degrees)'),endAngle:num('Arc end (degrees); absolute span > 0 and < 360'),closure:choice('Arc closure',['sector','segment'])};
const transform={positionMode:choice('relative offset or absolute bounding-box center after rotation/scaling',['relative','absolute']),x:length('X translation'),y:length('Y translation'),z:length('Z translation'),rx:num('X rotation (degrees)'),ry:num('Y rotation (degrees)'),rz:num('Z rotation (degrees)'),scale:num('Uniform dimensionless scale',{exclusiveMinimum:0})};
const op=(description,refs,properties,required=[],notes='')=>({description,refs,paramsSchema:{type:'object',properties,required,additionalProperties:false},notes});
export const operationCatalog={
 version:1,units:{length:'mm',angle:'degrees',volume:'mm^3',scale:'dimensionless'},
 usage:'Call webcad_get_state, use current body IDs as refs, then webcad_add_feature with op/params/refs/name and expectedRevision. Re-read revision after success. Schema describes accepted parameters, not a substitute for kernel geometric validation.',
 topology:'faceId, faceIds and edgeIds are zero-based indices of the CURRENT referenced body. body.faceCount/edgeCount define the range. Use current selectedTopology (when available) to identify user-picked face/edge/point. queryGeometry or measure returns exact BRep face type and measures. Counts alone do not identify spatial meaning. Do not guess face orientation. Rebuild may renumber topology; do not reuse IDs across revisions without reinspection. Unified logo accepts one exact planar or supported curved face; faceHole and faceExtrude require planar faces.',
 refs:'Creation uses refs:[]; single-body operations require exactly one current body ID; boolean operations require >=2 ordered IDs. Modifying operations consume refs and create a replacement body; copy preserves original; mirror/extractSolid preserve by default. Arrays/split create a compound, not separate feature rows.',
 refresh:'webcad_refresh rebuilds the existing document and updates the view. It does not append a feature or undo-history entry; it DOES increment revision, so use the returned revision for the next operation.',
 operations:{
 autoRound:op('整件圆边 / Round every sharp edge of one solid',1,{radius:positive('Uniform exact radius in mm')},['radius'],'Detect every sharp edge including holes and lettering, skip tangent seams and solve together. Fail atomically if any required edge cannot be rounded. No automatic smaller radius or partial success. Edit radius in the same feature to rebuild from its source, not the already-rounded result.'),
 smoothTransition:op('平滑过渡 / Smooth shared seams of adjacent faces together',1,{radius:positive('Exact transition radius; no automatic reduction'),faceIds:{...ids,minItems:2,maxItems:128,uniqueItems:true}},['radius','faceIds'],'Select at least two adjacent faces of one solid. Only their shared sharp edges are processed; boundary edges against unselected faces are not implicitly selected. All selected sharp seams are solved together with rolling-ball fillets. Valid solid and sampled normal checks reject remaining selected sharp seams or unexplained new sharp seams. Local blend terminations on unselected faces may remain sharp and are explicitly reported as boundarySharpEdges. getState().bodies[].transitionReport reports processed source edges and remaining sharp edges in the result. Existing unselected sharp edges (including lettering) remain; no whole-product safety certification, G2 guarantee or radius auto-reduction.'),
 logo:op('Unified reviewed LOGO on one exact face; legacy entries remain planar',1,{faceId:integer('Current selected face index'),point:point3,placementVersion:{type:'integer',const:2},targetSurfaceType:{type:'string',minLength:1,maxLength:40},targetFaceArea:num('Area of target face at placement (mm^2)',{exclusiveMinimum:0}),targetFaceCenter:point3,targetFaceSignature:{type:'string',minLength:12,maxLength:100},targetGeometryFingerprint:{type:'string',minLength:12,maxLength:100},mode:choice('Material operation',['engrave','emboss']),depth:positive('Explicit engraving depth or emboss height'),draftAngle:num('Draft angle degrees; legacy missing value means 0; unified UI initially 0',{minimum:0,exclusiveMaximum:45}),scale:num('Uniform outline scale',{exclusiveMinimum:0}),angle:num('Local rotation in degrees'),offsetX:length('Offset along local face X'),offsetY:length('Offset along local face Y'),mirrorX:flag('Mirror outline local X before rotation'),regions:{type:'array',minItems:1,maxItems:150,items:{type:'object',required:['outer'],properties:{outer:{type:'array',minItems:3,maxItems:2000,items:{type:'array',items:{type:'number'},minItems:2,maxItems:2}},holes:{type:'array',items:{type:'array',minItems:3,maxItems:2000,items:{type:'array',items:{type:'number'},minItems:2,maxItems:2}}}}}},source:{type:'object',description:'New v2 requires source.reviewed=true after contour/size/hole review; preserve original provenance'},name:{type:'string'},sizeMm:{type:'array',items:{type:'number'}}},['faceId','mode','depth','regions'],'New unified placement uses placementVersion:2, explicit world point and source.reviewed=true; WebCAD records exact face type/area/center, stable face signature for reloaded history and current BRep hash for creation audit, then dispatches planar or curved engraving. Curved emboss and draft remain unsupported. Missing placementVersion retains legacy planar semantics and missing draft defaults to 0. Source coordinates are centered X-right/Y-up mm. Local X is projected global X, or Y near X-aligned normal; local Y=normal cross X. Mirror, scale, rotate, then offset. Holes preserved; 12000 vertices total. Reject boundary, seam, invalid geometry or stale face.'),
 slot:op('Cut an exact capsule slot (two semicircles and two straight sides)',1,{length:positive('Overall slot length, including round ends'),width:positive('Slot width'),depth:positive('Cut depth'),x:length('Cutter start center X'),y:length('Cutter start center Y'),z:length('Cutter start center Z'),axis,direction:{type:'number',enum:[1,-1]},angle:num('Rotation in degrees about positive cut axis')},['length','width','depth'],'length >= width; equality gives a circular hole. Defaults center=origin,axis=Z,direction=1,angle=0. Unrotated long direction: Z axis -> +X; X axis -> +Y; Y axis -> +Z. Angle always follows the right-hand rule about the positive axis, independent of direction. Depth extends from the start plane along direction * axis. Must remove material. No automatic through depth.'),
 multiPocket:op('Cut multiple exact rectangular or rounded rectangular pockets',1,{depth:positive('Shared cut depth'),axis,direction:{type:'number',enum:[1,-1]},pockets:{type:'array',minItems:1,maxItems:64,items:{type:'object',required:['x','y','z','width','height'],additionalProperties:false,properties:{x:length('World cutter start center X'),y:length('World cutter start center Y'),z:length('World cutter start center Z'),width:positive('Pocket width in the first in-plane axis'),height:positive('Pocket height in the second in-plane axis'),cornerRadius:length('Optional corner radius; 0 means square corners',{minimum:0})}}}},['depth','pockets'],'Each pocket is centered at world XYZ on a plane normal to axis and cuts along direction * axis. Defaults axis=Z,direction=-1,cornerRadius=0. In-plane width/height directions: Z -> X/Y; X -> Y/Z; Y -> Z/X. Rounded corners require cornerRadius < half the shorter side. Every pocket must remove remaining material; the entire feature fails atomically otherwise. No automatic through depth or inferred surface.'),
 multiBoss:op('Fuse multiple exact solid cylindrical bosses onto one body',1,{radius:positive('Shared boss radius'),height:positive('Shared boss height'),axis,direction:{type:'number',enum:[1,-1]},points:{type:'array',minItems:1,maxItems:64,items:point3}},['radius','height','points'],'Every world XYZ point is a boss base center. Cylinder grows along signed X/Y/Z axis. Defaults axis=Z,direction=1. Each boss must add material and fuse into one solid; the whole feature fails atomically otherwise. Solid bosses only: drill holes in a separate multiHole step. No inferred face or automatic fillet.'),
 box:op('Box from [0,0,0] to [width,depth,height]',0,{width:positive('Width'),depth:positive('Depth'),height:positive('Height')},['width','depth','height']),
 cylinder:op('Cylinder on +Z from origin',0,{radius:positive('Radius'),height:positive('Height')},['radius','height']),
 sphere:op('Sphere centered at origin',0,{radius:positive('Radius')},['radius']),
 cone:op('Cone/frustum along +Z',0,{radius1:length('Bottom radius',{minimum:0}),radius2:length('Top radius',{minimum:0}),height:positive('Height')},['height'],'At least one radius >0. Defaults radius1=10,radius2=0.'),
 torus:op('Torus around Z axis',0,{majorRadius:positive('Major radius'),minorRadius:positive('Tube radius')},['majorRadius','minorRadius'],'majorRadius > minorRadius'),
 extrude:op('Extrude a closed profile normal to the chosen plane',0,{...profiles,plane,height:length('Signed nonzero extrusion')},['height'],'Rectangle/circle are centered profiles. Polygon points are plane coordinates. Profile defaults rectangle; plane XY. Rounded rectangle and arc also supported.'),
 revolve:op('Revolve a closed profile',0,{...profiles,plane,offset:length('Horizontal in-plane offset from rotation axis'),angle},[],'XY revolves about global Y; XZ/YZ about global Z. Defaults angle=360,offset=10; avoid crossing rotation axis.'),
 sweep:op('Sweep profile along a 3D polyline',0,{...profiles,profile:choice('Cross-section',['circle','rectangle','roundedRectangle','arc']),points:{type:'array',minItems:2,maxItems:100,items:point3}},['points'],'Use circle/rectangle/roundedRectangle/arc profile. points are the PATH, so polygon profile is not suitable for this API. Consecutive path points must differ. Profile is normal to first segment.'),
 loft:op('Ruled loft between parallel XY profiles',0,{profile:choice('Profile',['circle','rectangle']),radius:positive('Start radius'),width:positive('Start width'),depth:positive('Start depth'),endRadius:positive('End radius'),endWidth:positive('End width'),endDepth:positive('End depth'),height:length('Signed nonzero Z spacing'),offsetX:length('End X offset'),offsetY:length('End Y offset')},['profile','height'],'Missing end dimensions use corresponding start dimensions.'),
 transform:op('Scale, rotate X/Y/Z about origin, then translate',1,transform,[],'Defaults relative translations/angles=0,scale=1. Absolute mode requires XYZ and places final bounding-box center there. Rotation and scale are about world origin. Replaces original.'),
 copy:op('Copy with scale, rotation and translation',1,transform,[],'Preserves original; defaults same as transform.'),
 mirror:op('Mirror across a global origin plane',1,{plane,keepOriginal:flag('Preserve original; default true')},[],'Default plane XY.'),
 hole:op('Cylindrical cut starting at global coordinates',1,{radius:positive('Hole radius'),depth:positive('Hole depth'),x:length('Start X'),y:length('Start Y'),z:length('Start Z'),axis,direction:{type:'number',enum:[1,-1]}},['radius','depth'],'Start defaults origin,axis=Z,direction=1. Must remove material.'),
 multiHole:op('Cut cylindrical holes sequentially at multiple global start points',1,{radius:positive('Shared hole radius'),depth:positive('Shared hole depth'),axis,direction:{type:'number',enum:[1,-1]},points:{type:'array',minItems:1,maxItems:100,items:point3}},['radius','depth','points'],'One referenced body. Each point is a cutter START [x,y,z], not a face identifier or 2D sketch point. All holes share radius/depth/axis/direction. Defaults axis=Z,direction=1. Every hole must remove material from the sequential result; an off-body or already-empty hole fails the whole feature. Does not create threads.'),
 faceHole:op('Drill inward from a planar face',1,{faceId:integer('Planar face index'),point:point3,radius:positive('Hole radius'),depth:positive('Hole depth unless through'),through:flag('Through body')},['faceId','point','radius'],'Explicit world point required and must lie inside/on selected face; no automatic center. through=true computes sufficient depth from body bounds; otherwise supply depth.'),
 faceExtrude:op('Push/pull a planar face along its normal',1,{faceId:integer('Planar face index'),height:length('Signed nonzero height')},['faceId','height'],'Positive fuses outward material; negative cuts inward.'),
 linearPattern:op('Linear copies as one compound',1,{count:integer('Count including original',2,100),dx:length('Per-copy X step'),dy:length('Per-copy Y step'),dz:length('Per-copy Z step')},[],'Defaults count=3; at least one step nonzero.'),
 circularPattern:op('Rotated copies as one compound',1,{count:integer('Count including original',2,100),angle,axis,cx:length('Axis center X'),cy:length('Axis center Y'),cz:length('Axis center Z')},[],'Defaults count=3,angle=360,axis=Z,center=origin. Full circle excludes duplicate endpoint; partial angle includes both endpoints.'),
 group:op('Group bodies as a compound without fusing', '>=2',{},[],'Preserves constituent solid boundaries and positions. UI explode creates separate extractSolid features in one undo transaction. Already-fused single solids cannot be ungrouped into their original components.'),
 union:op('Fuse bodies','>=2',{},[],'Refs processed in order.'),
 cut:op('Subtract other bodies from first','>=2',{},[],'refs[0] is target; all subsequent refs are cutting tools.'),
 intersect:op('Common volume of bodies','>=2',{},[]),
 fillet:op('Round selected edges, all boundary edges of selected faces, or all body edges',1,{radius:positive('Fillet radius'),edgeIds:{...ids,minItems:0},faceIds:{...ids,minItems:0},allEdges:flag('Explicitly process all body edges')},['radius'],'Choose exactly one scope: nonempty edgeIds, nonempty faceIds (all boundary edges of those exact current faces, including holes), or allEdges=true. The radius may fail for tight corners or thin bodies; no automatic reduction.'),
 chamfer:op('Chamfer selected edges, face boundaries, or all body edges',1,{distance:positive('Chamfer distance'),edgeIds:{...ids,minItems:0},faceIds:{...ids,minItems:0},allEdges:flag('Explicitly process all body edges')},['distance'],'Choose exactly one scope: nonempty edgeIds, nonempty faceIds (all boundary edges of those exact current faces, including holes), or allEdges=true. No automatic distance reduction.'),
 shell:op('Hollow body removing selected faces',1,{thickness:length('Signed nonzero wall thickness'),faceIds:ids},['thickness','faceIds'],'Positive thickness produces inward shell. Current UI selected faces may supply IDs.'),
 split:op('Split body by an offset global plane',1,{plane,offset:length('Plane offset')},[],'Plane must cross interior. Produces compound with both halves.'),
 extractSolid:op('Extract one solid from a compound',1,{solidIndex:integer('Zero-based solid index'),keepOriginal:flag('Preserve source; default true')},[],'Use body.solidCount; default index=0.'),
 quickModel:{description:'Parameterized product model; prefer webcad_get_templates then webcad_apply_template',refs:0,paramsSchema:{type:'object',properties:{kind:{type:'string'}},required:['kind'],additionalProperties:true},notes:'Template-specific parameters and defaults come from get_templates, not arbitrary geometry code.'},
 remove:{description:'Use dedicated webcad_remove tool with ids, not add_feature',refs:'>=1',mcpAddFeature:false},
 import:{description:'Open STEP/BREP through browser file picker; MCP has no arbitrary filesystem access',refs:0,mcpAddFeature:false}
 }
};



operationCatalog.operations.vectorProfile={description:'Create independent planar faces or solids from closed vector regions',refs:0,paramsSchema:{type:'object',additionalProperties:false,required:['regions','output'],properties:{regions:operationCatalog.operations.logo.paramsSchema.properties.regions,source:{type:'object'},name:{type:'string'},sizeMm:{type:'array',items:{type:'number'}},areaMm2:{type:'number'},output:choice('Output geometry',['face','solid']),plane,scale:positive('Contour scale'),angle:num('In-plane angle'),height:length('Nonzero signed extrusion height for solid'),x:length('Contour center world X'),y:length('Contour center world Y'),z:length('Contour center world Z')}},notes:'No selected body needed. Closed regions and holes only; normalize imported bounds center to origin before position. XY normal +Z, XZ normal -Y, YZ normal +X. Curves are approximated at source import tolerance. Face output has zero solids; change output to solid and height to extrude later.'};
const analyticSegment={type:'object',additionalProperties:false,required:['type','points'],properties:{type:choice('Exact edge type',['line','arc']),points:{type:'array',items:point2,minItems:2,maxItems:3}}};
const analyticLoop={type:'array',items:analyticSegment,minItems:2,maxItems:128};
operationCatalog.operations.arcProfile={description:'Extrude exact closed XY LINE/ARC boundaries with optional holes',refs:0,paramsSchema:{type:'object',additionalProperties:false,required:['outer','height'],properties:{outer:analyticLoop,holes:{type:'array',items:analyticLoop,maxItems:16},height:length('Signed nonzero Z extrusion'),source:{type:'object'}}},notes:'Ordered line start/end or arc start/middle/end XY points. Each adjacent endpoint and closure must agree within 0.000001 mm. Output is one exact BRep solid; holes must remove material. Supports XY only, constant Z depth, no spline, variable thickness or source-DXF auto selection. Invalid topology rejects the step.'};
Object.assign(operationCatalog.operations,advancedOperations(operationCatalog.operations.logo.paramsSchema.properties.regions));
Object.assign(operationCatalog.operations,referenceOperations);
Object.assign(operationCatalog.operations,referenceProfileOperations);
