/** Machine-readable help only; the existing browser/kernel remains the operation authority. */
import { advancedOperations } from './advanced-operation-catalog.js';
import { referenceOperations } from './reference-tool-fields.js';
import { referenceProfileOperations } from './reference-profile-tools.js';
import { mechanicalOperations } from './mechanical-tool-contracts.js';
const num=(description,extra={})=>({type:'number',description,...extra});
const length=(description,extra={})=>num(description+' (mm)',extra);
const positive=description=>length(description,{exclusiveMinimum:0});
const integer=(description,minimum=0,maximum)=>({type:'integer',description,minimum,...(maximum===undefined?{}:{maximum})});
const choice=(description,values)=>({type:'string',description,enum:values});
const flag=description=>({type:'boolean',description});
const ids={type:'array',items:integer('Zero-based topology index'),minItems:1};
const point3={type:'array',items:{type:'number'},minItems:3,maxItems:3,description:'World coordinate [x,y,z] in mm'};
const point2={type:'array',items:{type:'number'},minItems:2,maxItems:2,description:'XY coordinate in mm'};
const plane=choice('Global plane',['XY','XZ','YZ']);
const axis=choice('Global axis',['X','Y','Z']);
const angle=num('Degrees',{exclusiveMinimum:0,maximum:360});
const profiles={profile:choice('Closed cross-section',['rectangle','circle','polygon','roundedRectangle','arc']),width:positive('Width'),depth:positive('Depth'),radius:positive('Circle/arc radius'),cornerRadius:positive('Rounded rectangle corner radius; less than half shorter side'),points:{type:'array',minItems:3,maxItems:1000,items:{type:'array',items:{type:'number'},minItems:2,maxItems:2}},startAngle:num('Arc start (degrees)'),endAngle:num('Arc end (degrees); absolute span > 0 and < 360'),closure:choice('Arc closure',['sector','segment'])};
const transform={positionMode:choice('relative offset or absolute bounding-box center after rotation/scaling',['relative','absolute']),x:length('X translation'),y:length('Y translation'),z:length('Z translation'),rx:num('X rotation (degrees)'),ry:num('Y rotation (degrees)'),rz:num('Z rotation (degrees)'),scale:num('Uniform dimensionless scale',{exclusiveMinimum:0}),mode:choice('Explicit spatial mode',['translate','toPoint','rotate','scale','align']),delta:point3,targetPoint:point3,orientation:choice('Preserve or align to work frame',['preserve','align-frame']),pivot:point3,axisVector:point3,angleDeg:num('Signed rotation angle (degrees)'),sourcePoint:point3,sourceAxis:point3,sourceUp:point3,targetAxis:point3,targetUp:point3,axisRelation:choice('Same or opposite axis direction',['same','opposite']),gapMm:length('Signed gap along target axis'),twistAngleDeg:num('Explicit in-plane twist angle (degrees)')};
const op=(description,refs,properties,required=[],notes='')=>({description,refs,paramsSchema:{type:'object',properties,required,additionalProperties:false},notes});
export const operationCatalog={
 version:1,units:{length:'mm',angle:'degrees',volume:'mm^3',scale:'dimensionless'},
 usage:'Call webcad_get_state, use current body IDs as refs, then webcad_add_feature with op/params/refs/name and expectedRevision. Re-read revision after success. Schema describes accepted parameters, not a substitute for kernel geometric validation.',
 topology:'faceId, faceIds and edgeIds are zero-based indices of the CURRENT referenced body. body.faceCount/edgeCount define the range. Use current selectedTopology (when available) to identify user-picked face/edge/point. queryGeometry or measure returns exact BRep face type and measures. Counts alone do not identify spatial meaning. Do not guess face orientation. Rebuild may renumber topology; do not reuse IDs across revisions without reinspection. Unified logo accepts one exact planar or supported curved face; faceHole and faceExtrude require planar faces.',
 refs:'Creation uses refs:[]; single-body operations require exactly one current body ID; boolean operations require >=2 ordered IDs. Modifying operations consume refs and create a replacement body; copy preserves original; mirror/extractSolid preserve by default. Arrays/split create a compound, not separate feature rows.',
 refresh:'webcad_refresh rebuilds the existing document and updates the view. It does not append a feature or undo-history entry; it DOES increment revision, so use the returned revision for the next operation.',
 operations:{
 reliefShoulder:op('浮雕中央肩部 / Central relief shoulder',1,{faceId:integer('Current lower step face'),point:point3,widthMm:positive('Axial transition width'),endProtectionMm:positive('Retained length at each angular end'),endPolicy:choice('Explicit end treatment',['retained-step-with-planar-caps'])},['faceId','point','widthMm','endProtectionMm','endPolicy'],'Native Services required. Bounded coaxial outward cylindrical layer under rigid pose; select an interior point on its lower four-edge step with circular boundaries and straight sides. Source dimensions are inferred. Removes material only across the central axial transition. Central support seams are G1; protected planar end caps are G0, not a whole-boundary fillet or fixed radius. Holes and all unselected faces are preserved. Fragmented boundaries and ambiguous support reject without approximation. Save includes the compiled result for offline reopen; recomputation requires Services.'),
 round:op('圆润 / Round',1,{edgeIds:{...ids,maxItems:32,uniqueItems:true},faceIds:{...ids,maxItems:16,uniqueItems:true},mode:choice('Automatic recognition or explicit treatment',['auto','edge','end']),strength:{type:'number',minimum:.1,maximum:1},radiusMm:positive('Optional exact edge radius; edge mode only'),depthMm:positive('Optional end rebuild depth'),axis,profileAxis:axis,direction:{type:'integer',enum:[1,-1]},directionEdgeId:{type:'integer',minimum:0}},[],'Unified rounding entrance. Select exactly one scope: edgeIds or faceIds. Planar faceIds resolve all current face boundary edges, including holes, with a 1000-edge budget; this scope uses edge mode and reports scope.faceIds/edgeIds. With configured Services, a rectangular face beside exactly one existing full-span round uses the accepted planar-boundary-cutter: six orthogonal support planes, one equal-radius cylindrical blend, no holes, width and depth greater than 4R, height greater than R. The source radius is retained when radiusMm is omitted; strength must remain .5 and does not scale this fixed-radius path. Four side sections retain R; corners are smooth freeform patches with four isolated termination points and are not constant-radius in every direction. Unsupported geometry is rejected without retry. Other automatic local face radii use measured support depth and body dimensions, not the shortest tessellated outline segment. Exact radiusMm is never reduced. Damaged contours must be explicitly corrected upstream; this tool never fills holes or removes profile points. Edge mode auto makes one geometry-based decision: an elongated principal-axis body selected wholly near its extreme end uses measured half-section end reconstruction, otherwise standard edge fillet. No solver fallback or radius search; one candidate per preview. strength defaults .5. End depth is measured and recommended. Optional explicit mode, radiusMm or depthMm, axis/direction/profileAxis and a straight principal-axis directionEdgeId on the same source resolve ambiguity. Only LINE/CIRCLE symmetric stable end sections are supported. End operation replaces the declared end and may add/remove material. Existing profile creases up to 1 degree are reported; new body join must meet sampled 0.1 degrees. A recommendation is not a feasibility guarantee. Read roundReport in preview.scope/getState.previewScope and bodies[].roundReport: mode, resolved parameters, control, scope, endRoundingReport or blendReport, attemptCount. Failure preserves the source.'),
 roundEnd:op('端头圆润 / Round free end',1,{edgeIds:{...ids,maxItems:32,uniqueItems:true},axis,direction:{type:'integer',enum:[1,-1],description:'End direction along the world axis'},profileAxis:choice('Cross-section thickness / rotation axis; different from axis',['X','Y','Z']),depthMm:positive('Distance from the actual extreme end back to the connection section')},['edgeIds','depthMm'],'Rebuild the whole end containing every selected edge by revolving its actual half section 180 degrees. Explicit axis/direction and profileAxis; no fixed R. Supports a single solid with a symmetric, stable straight LINE/CIRCLE section and no profile corner over 1 degree; ellipse and spline sections are unsupported. Preserves smaller inherited profile creases and reports them; not a whole-body G1/G2 claim. New body connection must meet 0.1 degrees; sampled position tolerance 1e-5 mm. Replaces material only inside the declared end region, may add and remove material, never extends overall length. Use preview.start/commit to inspect the full changed end. getState bodies[].endRoundingReport reports section checks, source/head/join angles, residual seams, target displacement, length and separate material changes. Wrong target, taper, asymmetry, insufficient depth, already rounded or invalid solid rejects atomically. World principal axes only; edit rebuilds from the original upstream body.'),
 rounding:op('圆角／圆润 / Rounding',1,{
   specVersion:{type:'integer',const:1},mode:choice('Rounding mode',['constant','variable','width']),
   scope:{type:'object',additionalProperties:false,required:['kind'],properties:{kind:choice('Target scope',['edges','face-boundaries','shared-faces','body']),edgeIds:{...ids,uniqueItems:true},faceIds:{...ids,uniqueItems:true},faceAIds:{...ids,uniqueItems:true},faceBIds:{...ids,uniqueItems:true},excludeEdgeIds:{...ids,uniqueItems:true,description:'Current source edge IDs excluded from this scope and any tangent propagation'}}},
   propagation:choice('Tangent chain selection',['selected-only','tangent-chain']),radiusMm:positive('Exact rolling-ball radius for constant mode'),
   laws:{type:'array',minItems:1,maxItems:1,items:{type:'object',additionalProperties:false,required:['chainId','direction','interpolation','stations'],properties:{chainId:{type:'string',minLength:6,maxLength:256,description:'One edge: edge:<id>; ordered collinear chain: edges:<id1>,<id2>,...'},direction:choice('Directed source edge',['forward','reverse']),interpolation:choice('Radius interpolation',['linear']),stations:{type:'array',minItems:2,maxItems:16,items:{type:'object',additionalProperties:false,required:['s','radiusMm'],properties:{s:{type:'number',minimum:0,maximum:1,description:'Normalized cumulative source arc length across the full ordered chain'},radiusMm:positive('Requested radius at station')}}}}}},
   widthAMm:positive('Width along support A in the local normal section'),widthBMm:positive('Width along support B in the local normal section'),
   boundaryRequirement:choice('End boundary validation',['standard']),
   endpoints:{type:'object',additionalProperties:false,required:['defaultMode'],properties:{defaultMode:choice('Open-chain termination',['natural'])}}
 },['specVersion','mode','scope','propagation','boundaryRequirement','endpoints'],
 'constant requires radiusMm. selected-only preserves the exact source-edge scope and rejects native contour expansion. tangent-chain permits a connected nonbranching G1 sharp-edge contour and reports every expanded source edge and generated face; preview the complete highlighted contour before applying. variable and width require selected-only. variable supports one straight edge or an ordered collinear chain of up to 16 sharp edges sharing two geometric support planes, with 2..16 ordered linear stations and explicit direction. chainId is edge:<id> or edges:<id1>,<id2>,... in scope order. Station s is normalized cumulative arc length across the whole chain. The ruled circular-section construction verifies final sections and sampled G1 support seams on real WASM. Piecewise-linear slope changes can create a station seam. Noncollinear chains and smooth laws remain unverified. width requires widthAMm and widthBMm and one edge or ordered shared-faces pair. A/B follow faceAIds/faceBIds; for one edge they follow ascending adjacent face IDs. Width families are a two-plane straight edge and a planar/cylindrical circular edge, either closed or an open arc bounded by radial planar end faces. When native constant R fails, an isolated BREP-copy same-domain cleanup is tried only for a uniquely remapped single edge with zero symmetric material difference, then exact-arc analytic fallback covers those constant-R families. Four-boundary constrained fill, other width geometries and non-natural endpoints remain unverified. Current topology indices must be queried from the source body.'),
 autoRound:op('整件圆边 / Round every sharp edge of one solid',1,{radius:positive('Uniform exact radius in mm')},['radius'],'Detect every sharp edge including holes and lettering, skip tangent seams and solve together. Fail atomically if any required edge cannot be rounded. No automatic smaller radius or partial success. Edit radius in the same feature to rebuild from its source, not the already-rounded result.'),
 smoothTransition:op('平滑过渡 / Smooth shared seams of adjacent faces together',1,{radius:positive('Exact transition radius; no automatic reduction'),faceIds:{...ids,minItems:2,maxItems:128,uniqueItems:true}},['radius','faceIds'],'Select at least two adjacent faces of one solid. Only their shared sharp edges are processed; boundary edges against unselected faces are not implicitly selected. All selected sharp seams are solved together with rolling-ball fillets. Valid solid and sampled normal checks reject remaining selected sharp seams or unexplained new sharp seams. Local blend terminations on unselected faces may remain sharp and are explicitly reported as boundarySharpEdges. getState().bodies[].transitionReport reports processed source edges and remaining sharp edges in the result. Existing unselected sharp edges (including lettering) remain; no whole-product safety certification, G2 guarantee or radius auto-reduction.'),
 logo:op('Unified reviewed LOGO on one exact face; legacy entries remain planar',1,{faceId:integer('Current selected face index'),point:point3,placementVersion:{type:'integer',const:2},targetSurfaceType:{type:'string',minLength:1,maxLength:40},targetFaceArea:num('Area of target face at placement (mm^2)',{exclusiveMinimum:0}),targetFaceCenter:point3,targetFaceSignature:{type:'string',minLength:12,maxLength:100},targetGeometryFingerprint:{type:'string',minLength:12,maxLength:100},mode:choice('Material operation',['engrave','emboss']),depth:positive('Explicit engraving depth or emboss height'),draftAngle:num('Draft angle degrees; legacy missing value means 0; unified UI initially 0',{minimum:0,exclusiveMaximum:45}),scale:num('Uniform outline scale',{exclusiveMinimum:0}),angle:num('Local rotation in degrees'),offsetX:length('Offset along local face X'),offsetY:length('Offset along local face Y'),mirrorX:flag('Mirror outline local X before rotation'),regions:{type:'array',minItems:1,maxItems:150,items:{type:'object',required:['outer'],properties:{outer:{type:'array',minItems:3,maxItems:2000,items:{type:'array',items:{type:'number'},minItems:2,maxItems:2}},holes:{type:'array',items:{type:'array',minItems:3,maxItems:2000,items:{type:'array',items:{type:'number'},minItems:2,maxItems:2}}}}}},source:{type:'object',description:'New v2 requires source.reviewed=true after contour/size/hole review; preserve original provenance'},name:{type:'string'},sizeMm:{type:'array',items:{type:'number'}}},['faceId','mode','depth','regions'],'New unified placement uses placementVersion:2, explicit world point and source.reviewed=true; WebCAD records exact face type/area/center, stable face signature for reloaded history and current BRep hash for creation audit, then dispatches planar or curved engraving. Curved emboss and draft remain unsupported. Missing placementVersion retains legacy planar semantics and missing draft defaults to 0. Source coordinates are centered X-right/Y-up mm. Local X is projected global X, or Y near X-aligned normal; local Y=normal cross X. Mirror, scale, rotate, then offset. Holes preserved; 12000 vertices total. Reject boundary, seam, invalid geometry or stale face.'),
 slot:op('Cut an exact capsule slot (two semicircles and two straight sides)',1,{length:positive('Overall slot length, including round ends'),width:positive('Slot width'),depth:positive('Cut depth'),x:length('Cutter start center X'),y:length('Cutter start center Y'),z:length('Cutter start center Z'),axis,direction:{type:'number',enum:[1,-1]},angle:num('Rotation in degrees about positive cut axis')},['length','width','depth'],'length >= width; equality gives a circular hole. Defaults center=origin,axis=Z,direction=1,angle=0. Unrotated long direction: Z axis -> +X; X axis -> +Y; Y axis -> +Z. Angle always follows the right-hand rule about the positive axis, independent of direction. Depth extends from the start plane along direction * axis. Must remove material. No automatic through depth.'),
 multiPocket:op('Cut multiple exact rectangular or rounded rectangular pockets',1,{depth:positive('Shared cut depth'),axis,direction:{type:'number',enum:[1,-1]},pockets:{type:'array',minItems:1,maxItems:64,items:{type:'object',required:['x','y','z','width','height'],additionalProperties:false,properties:{x:length('World cutter start center X'),y:length('World cutter start center Y'),z:length('World cutter start center Z'),width:positive('Pocket width in the first in-plane axis'),height:positive('Pocket height in the second in-plane axis'),cornerRadius:length('Optional corner radius; 0 means square corners',{minimum:0})}}}},['depth','pockets'],'Each pocket is centered at world XYZ on a plane normal to axis and cuts along direction * axis. Defaults axis=Z,direction=-1,cornerRadius=0. In-plane width/height directions: Z -> X/Y; X -> Y/Z; Y -> Z/X. Rounded corners require cornerRadius < half the shorter side. Every pocket must remove remaining material; the entire feature fails atomically otherwise. No automatic through depth or inferred surface.'),
 multiBoss:op('Fuse multiple exact solid cylindrical bosses onto one body',1,{radius:positive('Shared boss radius'),height:positive('Shared boss height'),axis,direction:{type:'number',enum:[1,-1]},points:{type:'array',minItems:1,maxItems:64,items:point3}},['radius','height','points'],'Every world XYZ point is a boss base center. Cylinder grows along signed X/Y/Z axis. Defaults axis=Z,direction=1. Each boss must add material and fuse into one solid; the whole feature fails atomically otherwise. Solid bosses only: drill holes in a separate multiHole step. No inferred face or automatic fillet.'),
 box:op('Box from [0,0,0] to [width,depth,height]',0,{width:positive('Width'),depth:positive('Depth'),height:positive('Height')},['width','depth','height']),
 cylinder:op('Cylinder on +Z from origin',0,{radius:positive('Radius'),height:positive('Height')},['radius','height']),
 sphere:op('Sphere centered at origin',0,{radius:positive('Radius')},['radius']),
 cone:op('Cone/frustum along +Z',0,{radius1:length('Bottom radius',{minimum:0}),radius2:length('Top radius',{minimum:0}),height:positive('Height')},['height'],'At least one radius >0. Defaults radius1=10,radius2=0.'),
 torus:op('Torus around Z axis',0,{majorRadius:positive('Major radius'),minorRadius:positive('Tube radius')},['majorRadius','minorRadius'],'majorRadius > minorRadius'),
 extrude:op('Extrude a closed profile normal to the chosen plane',0,{...profiles,plane,height:length('Signed nonzero extrusion')},['height'],'Rectangle/circle are centered profiles. Polygon points are plane coordinates. Profile defaults rectangle; plane XY. Rounded rectangle and arc also supported.'),
 revolve:op('Revolve a closed profile',0,{...profiles,plane,offset:length('Horizontal in-plane offset from rotation axis'),angle},[],'XY revolves about global Y; XZ/YZ about global Z. Defaults angle=360,offset=10; avoid crossing rotation axis.'),
 sweep:op('Sweep profile along a 3D polyline',0,{...profiles,profile:choice('Cross-section',['circle','rectangle','roundedRectangle','arc']),points:{type:'array',minItems:2,maxItems:100,items:point3}},['points'],'Use circle/rectangle/roundedRectangle/arc profile. points are the PATH, so polygon profile is not suitable for this API. Consecutive path points must differ. Profile is normal to first segment.'),
 loft:op('Ruled loft between parallel XY profiles',0,{profile:choice('Profile',['circle','rectangle']),radius:positive('Start radius'),width:positive('Start width'),depth:positive('Start depth'),endRadius:positive('End radius'),endWidth:positive('End width'),endDepth:positive('End depth'),height:length('Signed nonzero Z spacing'),offsetX:length('End X offset'),offsetY:length('End Y offset')},['profile','height'],'Missing end dimensions use corresponding start dimensions.'),
 transform:op('Scale, rotate X/Y/Z about origin, then translate',1,transform,[],'Defaults relative translations/angles=0,scale=1. Absolute mode requires XYZ and places final bounding-box center there. Rotation and scale are about world origin. Replaces original.'),
 copy:op('Copy with scale, rotation and translation',1,transform,[],'Preserves original; defaults same as transform.'),
 mirror:op('Mirror across a coordinate plane at an explicit offset',1,{plane,offsetMm:length('Signed plane coordinate; XY=Z, XZ=Y, YZ=X'),keepOriginal:flag('Preserve original as a mirror copy; default false')},[],'Defaults plane=XY, offsetMm=0, keepOriginal=false. The mirror replaces its input by default; explicitly set keepOriginal=true to create a mirror copy. Offset is the signed coordinate along the corresponding positive coordinate axis. Explicit placement uses the frozen local frame; omitted placement retains global coordinates.'),
 hole:op('Cylindrical cut starting at global coordinates',1,{radius:positive('Hole radius'),depth:positive('Hole depth'),x:length('Start X'),y:length('Start Y'),z:length('Start Z'),axis,direction:{type:'number',enum:[1,-1]}},['radius','depth'],'Start defaults origin,axis=Z,direction=1. Must remove material.'),
 holeWizard:op('Exact plain, counterbore, or countersink hole with flat or angled blind drill point',1,{kind:choice('Hole type',['plain','counterbore','countersink']),diameterMm:positive('Small hole diameter'),depthMm:positive('Blind depth according to depthReference'),through:flag('Through body along drilling axis'),drillPoint:choice('Blind bottom shape; omitted means flat',['flat','angled']),drillPointAngleDeg:num('Drill tip included angle; angled default 118 degrees',{exclusiveMinimum:0,exclusiveMaximum:179,default:118}),depthReference:choice('Angled blind depth: cylindrical segment length or total entrance-to-tip depth',['cylindricalLength','tipDepth']),recessDiameterMm:positive('Counterbore/countersink opening diameter'),recessDepthMm:positive('Counterbore depth'),includedAngleDeg:num('Countersink included angle in degrees',{exclusiveMinimum:0,exclusiveMaximum:179}),x:length('Cutter entrance X'),y:length('Cutter entrance Y'),z:length('Cutter entrance Z'),axis,direction:{type:'number',enum:[1,-1]}},['kind','diameterMm','through','x','y','z'],'One current solid target. Start point must lie on the boundary and direction enter continuous material. Blind depth including tip must stop before its first exit. Legacy/omitted drillPoint is flat. Angled blind tip height=diameter/(2*tan(drillPointAngleDeg/2)); default angle 118 deg, depthReference defaults cylindricalLength (tip is additional). tipDepth includes the tip and must leave positive cylinder length. Through holes reject angled tips. Recess must fit within cylindrical segment. Counterbore uses recessDepthMm; countersink derives depth (D-d)/(2*tan(includedAngle/2)). No modeled thread geometry.'),
 multiHole:op('Cut cylindrical holes sequentially at multiple global start points',1,{radius:positive('Shared hole radius'),depth:positive('Shared hole depth'),axis,direction:{type:'number',enum:[1,-1]},points:{type:'array',minItems:1,maxItems:100,items:point3}},['radius','depth','points'],'One referenced body. Each point is a cutter START [x,y,z], not a face identifier or 2D sketch point. All holes share radius/depth/axis/direction. Defaults axis=Z,direction=1. Every hole must remove material from the sequential result; an off-body or already-empty hole fails the whole feature. Does not create threads.'),
 faceHole:op('Drill inward from a planar face',1,{faceId:integer('Planar face index'),point:point3,radius:positive('Hole radius'),depth:positive('Hole depth unless through'),through:flag('Through body')},['faceId','point','radius'],'Explicit world point required and must lie inside/on selected face; no automatic center. through=true computes sufficient depth from body bounds; otherwise supply depth.'),
 faceExtrude:op('Push/pull a planar face along its normal',1,{faceId:integer('Planar face index'),height:length('Signed nonzero height')},['faceId','height'],'Positive fuses outward material; negative cuts inward.'),
 linearPattern:op('Linear copies as a compound or explicitly fused solid',1,{count:integer('Count including original',2,100),dx:length('Per-copy X step'),dy:length('Per-copy Y step'),dz:length('Per-copy Z step'),outputMode:choice('Output type',['compound','fuse'])},[],'Defaults count=3, dx=dy=dz=0, outputMode=compound; at least one step must be nonzero. Fuse requires all copies to form one solid and fails without committing if disconnected. Placement transforms local step vectors.'),
 circularPattern:op('Rotated copies as a compound or explicitly fused solid',1,{count:integer('Count including original',2,100),angle,axis,cx:length('Axis center X'),cy:length('Axis center Y'),cz:length('Axis center Z'),outputMode:choice('Output type',['compound','fuse'])},[],'Defaults count=3,angle=360,axis=Z,center=origin,outputMode=compound. Full circle excludes duplicate endpoint; partial angle includes both endpoints. Fuse requires one connected solid. Placement transforms local axis and center.'),
 group:op('Group bodies as a compound without fusing', '>=2',{},[],'Preserves constituent solid boundaries and positions. UI explode creates separate extractSolid features in one undo transaction. Already-fused single solids cannot be ungrouped into their original components.'),
 union:op('Fuse bodies','>=2',{keepTools:flag('Keep original tools')},[],'refs[0] is the target. Optional keepTools preserves refs[1..] as separate original bodies. Each fusion must retain at least the volume of its largest operand and may not exceed their summed volume; GEOMETRY_INVALID rolls back a result outside this material range.'),
 cut:op('Subtract other bodies from first','>=2',{keepTools:flag('Keep original tools')},[],'refs[0] is the explicit target; refs[1..] are tools. Optional keepTools preserves tool bodies. Each cut must not increase target volume; GEOMETRY_INVALID rolls back an output outside this material range.'),
 intersect:op('Common volume of bodies','>=2',{keepTools:flag('Keep original tools')},[],'refs[0] is the explicit target. Optional keepTools preserves refs[1..] as separate original bodies. Each common is checked with adaptive exact-BRep volume integration: result volume must not exceed either input (tolerance 1e-7 mm³ + 1e-8 times the smaller input volume). A violation returns GEOMETRY_INVALID and preserves the prior model, even if BRepCheck reports valid. No automatic alternative Boolean is applied.'),
 fillet:op('Round sharp edges, shared face edges, face boundaries or the whole solid',1,{radius:positive('Fillet radius'),edgeIds:{...ids,minItems:0},faceIds:{...ids,minItems:0},sharedFaces:flag('With at least two faceIds, process only their common sharp edges; omitted/false preserves historical face-boundary scope'),allEdges:flag('Explicitly process every sharp edge of the body')},['radius'],'Choose exactly one scope: edgeIds, faceIds, or allEdges=true. For two or more faces use sharedFaces:true to round only shared edges. UI multi-face selection uses sharedFaces:true; one face selects its boundary including holes. Tangent seams, periodic seams and degenerate edges are excluded. Exact BRep p-curves determine surface normals. Failure reports target/failing edge IDs and commits nothing. For up to eight target edges, a failed radius can trigger bounded read-only trials of smaller radii; the error may report one sampled radius that produced a valid solid. It is not a maximum and is never silently applied. Convex corners remove material; concave corners add a blend inside the recess. getState().bodies[].blendReport returns processed/skipped edges.'),
 chamfer:op('Equal-distance, two-distance or distance-angle chamfer of sharp edges',1,{distance:positive('Distance on reference support face'),mode:choice('Omitted mode preserves equal-distance chamfer',['equalDistance','twoDistances','distanceAngle']),distance2:positive('Distance on other support face; required only for twoDistances'),angleDeg:num('Chamfer angle relative to reference face; required only for distanceAngle',{exclusiveMinimum:0,exclusiveMaximum:90}),flipDirection:flag('Use the other adjacent support face'),referenceFaceId:{type:'integer',minimum:0,description:'Optional current source face index incident to every selected edge; default first adjacent face in current topology order'},edgeIds:{...ids,minItems:0},faceIds:{...ids,minItems:0},sharedFaces:flag('With at least two faceIds, process only their common sharp edges; omitted/false preserves historical face-boundary scope'),allEdges:flag('Explicitly process every sharp edge of the body')},['distance'],'Choose exactly one scope: edgeIds, faceIds, or allEdges=true. sharedFaces:true selects their common sharp edges. Legacy/omitted mode is equalDistance. twoDistances requires distance2; distanceAngle requires angleDeg in (0,90), radians are converted only at kernel call. Opposite mode fields are rejected; equalDistance forbids asymmetric options. Asymmetric distance is on referenceFaceId, or first adjacent current source face; flipDirection uses the other face. Optional explicit reference face must touch every selected edge. Tangent/periodic seams and degenerate edges are excluded. Failure preserves source, never reduces dimensions. getState().bodies[].blendReport returns mode, processed/skipped edges and resolved supportFaces for asymmetric modes.'),
 shell:op('Hollow body removing selected faces',1,{thickness:length('Signed nonzero wall thickness'),faceIds:ids},['thickness','faceIds'],'Positive thickness produces inward shell. Current UI selected faces may supply IDs.'),
 split:op('Split body by an offset global plane',1,{plane,offset:length('Plane offset')},[],'Plane must cross interior. Produces compound with both halves.'),
 extractSolid:op('Extract one solid from a compound',1,{solidIndex:integer('Zero-based solid index'),keepOriginal:flag('Preserve source; default true')},[],'Use body.solidCount; default index=0.'),
 quickModel:{description:'Parameterized product model; prefer webcad_get_templates then webcad_apply_template',refs:0,paramsSchema:{type:'object',properties:{kind:{type:'string'}},required:['kind'],additionalProperties:true},notes:'Template-specific parameters and defaults come from get_templates, not arbitrary geometry code.'},
 remove:{description:'Use dedicated webcad_remove tool with ids, not add_feature',refs:'>=1',mcpAddFeature:false},
 import:{description:'Open STEP/BREP through browser file picker; MCP has no arbitrary filesystem access',refs:0,mcpAddFeature:false}
 }
};



operationCatalog.operations.vectorProfile={description:'Create independent planar faces or solids from closed vector regions',refs:0,paramsSchema:{type:'object',additionalProperties:false,required:['regions','output'],properties:{regions:operationCatalog.operations.logo.paramsSchema.properties.regions,source:{type:'object'},name:{type:'string'},sizeMm:{type:'array',items:{type:'number'}},areaMm2:{type:'number'},output:choice('Output geometry',['face','solid']),plane,scale:positive('Contour scale'),angle:num('In-plane angle'),height:length('Nonzero signed extrusion height for solid'),x:length('Contour center world X'),y:length('Contour center world Y'),z:length('Contour center world Z')}},notes:'No selected body needed. Closed regions and holes only; normalize imported bounds center to origin before position. XY normal +Z, XZ normal -Y, YZ normal +X. Curves are approximated at source import tolerance. Face output has zero solids; change output to solid and height to extrude later.'};
const analyticSegment={type:'object',additionalProperties:false,required:['type','points'],properties:{type:choice('Exact edge type',['line','arc']),points:{type:'array',items:point2,minItems:2,maxItems:3}}};
const analyticLoop={type:'array',items:analyticSegment,minItems:2,maxItems:256};
operationCatalog.operations.arcProfile={description:'Extrude exact closed XY LINE/ARC boundaries with optional holes',refs:0,paramsSchema:{type:'object',additionalProperties:false,required:['outer','height'],properties:{outer:analyticLoop,holes:{type:'array',items:analyticLoop,maxItems:16},height:length('Signed nonzero Z extrusion'),source:{type:'object'}}},notes:'Ordered line start/end or arc start/middle/end XY points. Each boundary accepts 2–256 segments; up to16 holes. Each adjacent endpoint and closure must agree within 0.000001 mm. Output is one exact BRep solid; holes must remove material. Supports XY only, constant Z depth, no spline, variable thickness or source-DXF auto selection. Invalid topology rejects the step.'};
const profileEntity={type:'object',additionalProperties:false,required:['id','type'],properties:{id:{type:'string',minLength:1,maxLength:64},type:choice('Analytic entity',['line','arc3','circle','rectangle','roundedRectangle','capsule']),originMm:point2,widthMm:positive('Primitive width or capsule overall length'),heightMm:positive('Primitive height or capsule width'),cornerRadiusMm:positive('Rounded rectangle corner radius'),startMm:point2,endMm:point2,midMm:point2,centerMm:point2,diameterMm:positive('Circle diameter'),construction:flag('Construction/reference geometry only'),projectionSource:{type:'object',description:'Frozen source B-Rep edge geometry and provenance; never automatically updates from the live source'}}};
const profileEdgeRef={type:'object',additionalProperties:false,required:['entityId','reversed'],properties:{entityId:{type:'string',minLength:1,maxLength:64},reversed:flag('Reverse analytic edge direction')}};
operationCatalog.operations.sketchProfile=op('Create an editable exact 2D wire or planar face from stable analytic entities',0,{profileVersion:{type:'integer',const:1},entities:{type:'array',minItems:1,maxItems:500,items:profileEntity},loops:{type:'array',maxItems:50,items:{type:'object',additionalProperties:false,required:['id','edges'],properties:{id:{type:'string',minLength:1,maxLength:64},edges:{type:'array',minItems:1,maxItems:500,items:profileEdgeRef}}}},chains:{type:'array',maxItems:50,items:{type:'object',additionalProperties:false,required:['id','edges'],properties:{id:{type:'string',minLength:1,maxLength:64},edges:{type:'array',minItems:1,maxItems:500,items:profileEdgeRef}}}},regions:{type:'array',maxItems:16,items:{type:'object',additionalProperties:false,required:['id','outerLoopId','holeLoopIds'],properties:{id:{type:'string',minLength:1,maxLength:64},outerLoopId:{type:'string',minLength:1,maxLength:64},holeLoopIds:{type:'array',maxItems:49,items:{type:'string',minLength:1,maxLength:64}}}}},output:choice('Editable geometry',['wire','face'])},['profileVersion','entities','output'],'Single planar sketch. Top-level placement freezes the current insertion frame; later anchor moves do not move this profile. Analytic line, three-point arc and circle remain exact. Rectangle, roundedRectangle and capsule store one parameter definition (originMm,widthMm,heightMm,cornerRadiusMm); stable analytic edges are derived, not separately edited until explicit conversion. Closed face requires explicit ordered loops and up to 16 disjoint regions; open wire uses ordered chains. Unsupported spline editing is rejected.');
operationCatalog.operations.profileOffset=op('Create an exact planar equidistant offset or band from one closed face',1,{distanceMm:positive('Equidistant offset'),side:choice('Offset direction',['inside','outside']),join:choice('Corner join',['intersection','round']),output:choice('Result',['wire','face','band'])},['distanceMm','side','join','output'],'Source face is preserved. A single planar unholed region is supported. Collapse, multiple outputs and ambiguous offsets are rejected; geometry is never scaled as a substitute.');
operationCatalog.operations.profileRepair=op('Derive a repaired analytic profile by moving one explicitly identified endpoint within the stated maximum displacement',1,{issueId:{type:'string',minLength:1,maxLength:150},maxEndpointMoveMm:{type:'number',exclusiveMinimum:0,maximum:1,description:'Maximum permitted movement of one endpoint in mm'}},['issueId','maxEndpointMoveMm'],'refs[0] is the current saved sketchProfile source. The source is preserved. The issueId must come from inspectProfile on this source and only an explicit endpoint gap is supported. Closing an open chain yields a face. Failure leaves the source untouched.');
operationCatalog.operations.profileExtrude=op('Extrude a placed exact profile into a new solid, join, cut or intersection',1,{operation:choice('Result mode',['newBody','join','cut','intersect']),extent:choice('Depth mode',['distance','throughSelected','toPlane']),distanceMm:positive('Explicit positive depth'),direction:{type:'integer',enum:[1,-1],description:'Positive or negative saved profile normal'},planePoint:{type:'array',minItems:3,maxItems:3,items:{type:'number'},description:'Fixed world point on infinite target plane'},planeNormal:{type:'array',minItems:3,maxItems:3,items:{type:'number'},description:'Fixed world plane normal'},allowanceMm:{type:'number',description:'Signed distance added along extrusion direction'}},['operation','extent','direction'],'refs[0] is the placed planar profile. newBody requires only that ref; join/cut/intersect require refs[1] as one explicit solid target. The profile remains in history and the target is replaced. throughSelected computes depth from that target only and refuses a cutter starting inside it. toPlane supports only a fixed world plane parallel to the source profile plus signed allowance; oblique end planes are explicitly rejected. It uses an infinite world plane; it does not claim the cutter stops at a finite face boundary. No active anchor transform is applied again.');
operationCatalog.operations.draftFaces=op('Exact restricted four-side planar prism draft around one fixed bottom plane',1,{faceIds:{type:'array',minItems:4,maxItems:4,uniqueItems:true,items:{type:'integer',minimum:0}},neutralFaceId:{type:'integer',minimum:0},pullDirection:{type:'array',minItems:3,maxItems:3,items:{type:'number'}},angleDeg:num('Draft angle degrees',{exclusiveMinimum:0,exclusiveMaximum:45})},['faceIds','neutralFaceId','pullDirection','angleDeg'],'One explicit six-plane twelve-edge single-solid prism target. Exactly all four side faces and fixed bottom must be listed. Source is not mutated; topology outside this verified subset is rejected. Preview before commit. Not a castability certification.');
Object.assign(operationCatalog.operations,advancedOperations(operationCatalog.operations.logo.paramsSchema.properties.regions));
Object.assign(operationCatalog.operations,referenceOperations);
Object.assign(operationCatalog.operations,referenceProfileOperations);
Object.assign(operationCatalog.operations,mechanicalOperations);

// Saved v1/v2 features and explicit legacy API calls retain their original contract.
export const legacyRoundingOperation=operationCatalog.operations.rounding;
export const legacyUnifiedRoundingOperation=op('圆角 / Round selected edges',1,{
  specVersion:{type:'integer',const:2},
  sizeMm:positive('Requested local rounding scale; exact-radius candidates use this as radius; supported adaptive candidates report their measured scale range'),
  scope:{type:'object',additionalProperties:false,required:['kind','edgeIds'],properties:{
    kind:{type:'string',const:'edges'},edgeIds:{...ids,maxItems:64,uniqueItems:true}
  }}
},['specVersion','sizeMm','scope'],'Select current sharp edges, set sizeMm, preview the actual affected region, then commit the validated preview. The solver first tries exact constant-radius construction, then a genuine nonconstant local smooth construction only for a supported geometry family. Algorithms and connected-edge resolution are internal. sizeMm is the unchanged requested rounding scale; adaptive dimensions may vary locally and must be measured and reported, never labeled as an exact radius or replaced by an unreported near-zero effect. The report exposes construction kind, requested scale, actual scale range, candidate attempts, and evidence for every contact/terminal seam, material direction and the local retained region. Unsupported families or failed quality checks do not commit and leave the source unchanged. This does not promise that all edge, support-surface or endpoint families are supported. Historical specVersion:1 features and the legacy fillet API retain their exact original semantics; new operations use this v2 contract.');
operationCatalog.operations.rounding=op('自动打磨 / Smooth selected sharp edges',1,{
  specVersion:{type:'integer',const:3},
  strength:{type:'number',exclusiveMinimum:0,maximum:1,default:1,unit:'1',quantityKind:'ratio',quantizationPolicy:'none',description:'Optional grinding strength as a dimensionless fraction of the locally feasible smoothing effect; defaults to 1. This is not a radius or a length.'},
  scope:{type:'object',additionalProperties:false,required:['kind','edgeIds'],properties:{
    kind:{type:'string',const:'edges'},edgeIds:{...ids,maxItems:64,uniqueItems:true}
  }}
},['specVersion','scope'],'Select current source edges and preview automatic local grinding. No sizeMm or exact-radius target is required. Optional strength is a dimensionless fraction in (0,1], default 1; the solver derives local dimensions from the source geometry. Related edges and support faces may follow only within the reported source-derived local region. The preview and committed roundingReport.region expose sourceBodyId, requestedEdgeIds, expandedEdgeIds and affectedFaceIds; verify this explicit expansion before committing the same preview. Every generated contact, inter-patch and terminal boundary must meet the original strict G0/G1, material and locality checks. Multiple smooth curved patches are permitted; valid topology alone is not acceptance. Unsupported geometry or failed evidence leaves the source unchanged. Historical specVersion:1 and specVersion:2 features retain their original parameters and solver semantics; do not reinterpret them as automatic grinding.');
