import { toolDisabledReason } from './tool-state.js';
import { METAL_FINISHES } from './metal-materials.js';
import { QUICK_MODELS } from './quick-models.js';
const createLogoImportUI=()=>{const node=document.createElement('p');node.textContent='CAPABILITY_UNAVAILABLE：静态版不提供服务器矢量文件转换；可使用已有标准 LOGO 数据。';return node;};
import { createDimensionCalculator } from './parameter-calculator-ui.js';
import { advancedNames, advancedFields, advancedNotes } from './advanced-tool-fields.js';
import { referenceNames, referenceFields, referenceNotes } from './reference-tool-fields.js';
import { addAdvancedField, readAdvancedJson } from './advanced-form-fields.js';
import { t, getLanguage, setLanguage, addTranslations, watchTranslations } from './i18n.js';
export { t } from './i18n.js';
addTranslations({
 '槽总长须大于或等于槽宽':'Overall slot length must be at least the slot width','创建':'Create','加工':'Modify','快速开始':'Start','布尔运算':'Boolean','孔与槽':'Holes & slots','面与边':'Faces & edges','拆分':'Separate','交互手柄':'Interactive transform','标准视角':'Standard views','显示方式':'Display','投影':'Projection','显示辅助':'Display aids','网格':'Grid','几何吸附':'Geometry snap',
 '清除选择':'Clear selection','外观与尺寸':'Appearance & dimensions','正在计算，请稍候':'Computing, please wait','建模内核尚未就绪':'Modeling kernel is not ready','按 Ctrl 或 Shift 依次选择至少两个实体':'Ctrl or Shift-select at least two bodies in order','此工具需要恰好选择一个实体':'Select exactly one body for this tool','请先选择要删除的实体':'Select bodies to remove','切换到选面，然后选择一个平面':'Switch to Face and select exactly one planar face','切换到选面，选择需要移除的开口面':'Switch to Face and select the opening faces to remove','请选择包含多个实体的复合体':'Select a compound containing multiple solids','请先创建或打开模型':'Create or open a model first',
 '从快捷模型、基本实体或打开 STEP 开始':'Start with a quick model, primitive, or open a STEP file','选择实体后可加工；Ctrl / Shift 多选':'Select a body to modify; Ctrl / Shift to select multiple','已选多个实体：可进行布尔运算或删除；其他加工请只选一个':'Multiple bodies: Boolean or delete; select one for other modifications','已选面：可打孔、面拉伸或抽壳':'Faces selected: drill, push/pull or shell','已选边：圆角和倒角仅处理这些边':'Edges selected: fillet and chamfer affect these edges only','已选一个实体：可加工、变换或编辑参数':'One body selected: modify, transform or edit parameters','正在编辑历史步骤；应用后会重建后续模型':'Editing a history step; applying rebuilds the dependent model',
 '相减顺序：先选保留主体，再选切除刀具':'Subtract in selection order: target first, then cutters','选面后移除开口面并生成壁厚':'Select opening faces to remove, then define wall thickness','选择指定边，或明确勾选全部边':'Fillet selected edges, or all edges when no edges are selected','选择指定边，或明确勾选全部边':'Modify selected edges, or all edges when none are selected','绘制闭合轮廓，随后拉伸成实体':'Draw a closed profile, then extrude it','在选定平面上向实体内部打孔':'Drill inward from the selected planar face','沿选定平面的法向增加或切除材料':'Add or cut material along the planar face normal'
});
addTranslations({"选择":"Select","移动":"Move","位置方式":"Position mode","相对位移":"Relative offset","绝对位置（包围盒中心）":"Absolute position (bounding-box center)","孔中心 X（全局）":"Hole center X (world)","孔中心 Y（全局）":"Hole center Y (world)","孔中心 Z（全局）":"Hole center Z (world)","X 位移 / 目标坐标":"X offset / target","Y 位移 / 目标坐标":"Y offset / target","Z 位移 / 目标坐标":"Z offset / target","目标中心 X":"Target center X","目标中心 Y":"Target center Y","目标中心 Z":"Target center Z","明确处理全部边":"Apply to all edges explicitly","请先选边，或明确勾选全部边。":"Select edges, or explicitly choose all edges.","选择指定边，或明确勾选全部边":"Select specific edges, or explicitly choose all edges","选择实体，关闭移动或旋转手柄":"Select bodies and turn off transform handles","先用鼠标点击平面的孔中心，再打开工具。下方显示点击位置的全局 X、Y、Z，可精确修改；孔中心必须位于所选平面内。先预览再确认。":"Click the hole center on a planar face first. Edit the picked world X/Y/Z below; the center must lie inside the selected face. Preview before applying.","相对位移：输入 X、Y、Z 移动量。绝对位置：将实体包围盒中心放到指定全局坐标。旋转和缩放以全局原点为基点；单位 mm / °。":"Relative offset: enter X/Y/Z movement. Absolute position: place the bounding-box center at the world coordinates. Rotation and scaling use the world origin; units mm / degrees.","保留原实体，并按全局 X、Y、Z 位移创建副本；旋转和缩放以全局原点为基点。":"Keep the source and copy using world X/Y/Z offsets. Rotation and scaling use the world origin.","沿经过全局原点的坐标平面镜像：YZ 为 X=0，XZ 为 Y=0，XY 为 Z=0；保留原实体。":"Mirror about a world-origin plane: YZ is X=0, XZ is Y=0, XY is Z=0. Keep the original.","先切换到边并选择需要倒圆的边；如需整件处理，请明确勾选全部边。半径过大可能无法生成。":"Select the edges to fillet, or explicitly choose all edges. Excessive radius may fail.","先切换到边并选择需要倒角的边；如需整件处理，请明确勾选全部边。":"Select the edges to chamfer, or explicitly choose all edges.","平面位置是全局坐标：XY 对应 Z，XZ 对应 Y，YZ 对应 X。分割保留两侧实体，结果为复合体。":"Plane position is a world coordinate: XY uses Z, XZ uses Y, YZ uses X. Keep both sides as a compound.","围绕指定全局 X、Y、Z 轴心和轴方向复制实体。数量包含原件；360° 均匀环绕，部分角度包含起点与终点；结果作为一个复合实体保存。":"Copy about the specified world X/Y/Z center and axis. Count includes the original. Full 360 degrees spaces evenly; partial angles include both ends. Save as a compound."});
addTranslations({'长方体从全局原点沿正 X、Y、Z 方向生成；创建后使用移动设置具体位置。':'Create from the world origin along positive X/Y/Z. Use Move afterward to set its position.','底面圆心位于全局原点，沿正 Z 方向生成；创建后使用移动设置具体位置。':'Base center is at the world origin; extend along positive Z. Use Move afterward to set its position.','球心位于全局原点；创建后使用移动设置具体位置。':'Sphere center is at the world origin. Use Move afterward to set its position.','圆环中心位于全局原点，轴向为 Z；创建后使用移动设置具体位置。':'Torus center is at the world origin, with axis Z. Use Move afterward to set its position.','面中心局部 X 偏移':'Local X offset from face center','面中心局部 Y 偏移':'Local Y offset from face center'});
const names = {box:'长方体',cylinder:'圆柱',sphere:'球体',cone:'圆锥',torus:'圆环',extrude:'拉伸',revolve:'旋转成型',transform:'移动 / 旋转',copy:'复制',mirror:'镜像',union:'合并',cut:'相减',intersect:'相交',fillet:'圆角',chamfer:'倒角',shell:'抽壳',hole:'打孔',linearPattern:'直线阵列',circularPattern:'环形阵列',remove:'删除',import:'导入'};
const fields = {
 vectorProfile:[['output','生成类型','solid',['solid','face']],['height','拉伸高度（负数反向）',5,'nonzero'],['plane','草图平面','XY',['XY','XZ','YZ']],['x','轮廓中心 X',0],['y','轮廓中心 Y',0],['z','轮廓中心 Z',0],['scale','轮廓比例',1,'positive'],['angle','平面内旋转角',0]],
 logo:[['mode','LOGO 加工方式','engrave',['engrave','emboss']],['depth','凹凸深度（核对尺寸）',0.2,'positive'],['draftAngle','脱模斜度（°）',7,'nonnegative'],['scale','LOGO 比例',1,'positive'],['angle','LOGO 旋转角',0],['offsetX','面中心局部 X 偏移',0],['offsetY','面中心局部 Y 偏移',0],['mirrorX','水平镜像',false,'boolean']],
 slot:[['length','槽总长',20,'positive'],['width','槽宽',6,'positive'],['depth','切入深度',5,'positive'],['x','起点 X',0],['y','起点 Y',0],['z','起点 Z',0],['axis','切入轴','Z',['X','Y','Z']],['direction','切入方向','1',['1','-1']],['angle','槽旋转角',0]],
 multiHole:[['radius','孔半径',2.5,'positive'],['depth','孔深',10,'positive'],['axis','钻孔轴','Z',['X','Y','Z']],['direction','钻孔方向','1',['1','-1']],['points','钻孔起点列表','10,10,0\n30,10,0','holePoints3']],
 faceHole:[['pointX','孔中心 X（全局）',''],['pointY','孔中心 Y（全局）',''],['pointZ','孔中心 Z（全局）',''],['radius','孔半径',2.5,'positive'],['depth','孔深',10,'positive'],['through','贯穿实体',false,'boolean']],
 faceExtrude:[['height','拉伸高度（负数反向）',5,'nonzero']],
 sweep:[['profile','轮廓','circle',['circle','rectangle']],['radius','轮廓半径',2,'positive'],['width','轮廓宽度',4,'positive'],['depth','轮廓深度',4,'positive'],['points','折线路径','0,0,0\n0,0,20\n15,0,30','points3']],
 loft:[['profile','轮廓','circle',['circle','rectangle']],['radius','轮廓半径',10,'positive'],['width','轮廓宽度',20,'positive'],['depth','轮廓深度',15,'positive'],['endRadius','末截面半径',5,'positive'],['endWidth','末截面宽度',10,'positive'],['endDepth','末截面深度',8,'positive'],['height','截面距离',30,'positive'],['offsetX','末截面 X 偏移',0],['offsetY','末截面 Y 偏移',0]],
 split:[['plane','分割平面','XY',['XY','XZ','YZ']],['offset','平面位置',0]],
 extractSolid:[['solidIndex','实体索引（从 0 开始）',0,'integer'],['keepOriginal','保留原复合体',true,'boolean']],
 section:[['axis','轴方向','Z',['X','Y','Z']],['position','平面位置',0],['enabled','启用',true,'boolean']],
 hole:[['radius','孔半径',2.5,'positive'],['depth','孔深',10,'positive'],['x','起点 X',0],['y','起点 Y',0],['z','起点 Z',0],['axis','钻孔轴','Z',['X','Y','Z']],['direction','钻孔方向','1',['1','-1']]],
 linearPattern:[['count','数量（包含原件）',3,'count'],['dx','每步 X 位移',30],['dy','每步 Y 位移',0],['dz','每步 Z 位移',0]],
 circularPattern:[['count','数量（包含原件）',6,'count'],['angle','分布角度',360,'angle'],['axis','旋转轴方向','Z',['X','Y','Z']],['cx','轴心 X',0],['cy','轴心 Y',0],['cz','轴心 Z',0]],
 box:[['width','宽度',40,'positive'],['depth','深度',20,'positive'],['height','高度',10,'positive']],
 cylinder:[['radius','半径',10,'positive'],['height','高度',30,'positive']],sphere:[['radius','半径',15,'positive']],
 cone:[['radius1','底部半径',15,'nonnegative'],['radius2','顶部半径',0,'nonnegative'],['height','高度',30,'positive']],
 torus:[['majorRadius','主半径',20,'positive'],['minorRadius','管半径',5,'positive']],
 extrude:[['profile','轮廓','rectangle',['rectangle','circle','polygon','roundedRectangle','arc']],['cornerRadius','外轮廓圆角',3,'nonnegative'],['startAngle','起始角',0],['endAngle','结束角',90],['closure','封闭方式','sector',['sector','segment']],['plane','草图平面','XY',['XY','XZ','YZ']],['width','轮廓宽度',30,'positive'],['depth','轮廓深度',20,'positive'],['radius','轮廓半径',10,'positive'],['points','多边形顶点','0,0\n30,0\n30,20\n0,20','points'],['height','拉伸高度（负数反向）',10,'nonzero']],
 revolve:[['profile','轮廓','rectangle',['rectangle','circle','polygon']],['plane','草图平面','XY',['XY','XZ','YZ']],['width','轮廓宽度',10,'positive'],['depth','轮廓深度',20,'positive'],['radius','轮廓半径',5,'positive'],['points','多边形顶点','0,0\n10,0\n10,20\n0,20','points'],['offset','距旋转轴',15,'nonnegative'],['angle','旋转角度',360,'angle']],
 transform:[['positionMode','位置方式','relative',['relative','absolute']],['x','X 位移 / 目标坐标',0],['y','Y 位移 / 目标坐标',0],['z','Z 位移 / 目标坐标',0],['rx','绕 X 轴旋转',0],['ry','绕 Y 轴旋转',0],['rz','绕 Z 轴旋转',0],['scale','等比缩放',1,'positive']],
 copy:[['x','X 位移',50],['y','Y 位移',0],['z','Z 位移',0],['rx','绕 X 轴旋转',0],['ry','绕 Y 轴旋转',0],['rz','绕 Z 轴旋转',0],['scale','等比缩放',1,'positive']],
 mirror:[['plane','镜像平面','YZ',['YZ','XZ','XY']]],fillet:[['radius','圆角半径',2,'positive'],['allEdges','明确处理全部边',false,'boolean']],chamfer:[['distance','倒角距离',1,'positive'],['allEdges','明确处理全部边',false,'boolean']],shell:[['thickness','壁厚',1,'positive']]
};
const choiceNames={rectangle:'矩形',circle:'圆形',polygon:'多边形',roundedRectangle:'圆角矩形',arc:'圆弧',sector:'扇形',segment:'弓形','1':'轴正方向','-1':'轴负方向'};
Object.assign(names,advancedNames); Object.assign(fields,advancedFields);
Object.assign(names,referenceNames); Object.assign(fields,referenceFields); Object.assign(advancedNotes,referenceNotes);
Object.assign(choiceNames,{shell:'曲面壳（未封口）',spline:'样条逼近'});
Object.assign(names,{vectorProfile:'导入路径'});Object.assign(choiceNames,{solid:'实体',face:'平面'});
addTranslations({'脱模斜度（°）':'Draft angle (degrees)','默认脱模斜度 7°，0° 为直壁；凹字向底部收窄，凸字向顶部收窄，承载面处轮廓保持原尺寸。':'Default draft is 7 degrees; 0 gives straight walls. Engraving narrows toward the bottom, embossing toward the top; the contour at the supporting face stays unchanged.'});
addTranslations({'导入路径':'Import paths','生成类型':'Generate','实体':'Solid','平面':'Face','轮廓中心 X':'Profile center X','轮廓中心 Y':'Profile center Y','轮廓中心 Z':'Profile center Z','轮廓比例':'Profile scale','平面内旋转角':'Rotation in plane','导入或粘贴闭合矢量路径，直接生成面或实体。轮廓包围盒中心放置于指定全局 XYZ；平面内缩放和旋转围绕此中心。':'Import or paste closed vector paths to create faces or solids. Place the profile bounding-box center at world XYZ; scale and rotate about this center.','请先导入或粘贴有效的闭合路径。':'Import or paste valid closed paths first.','独立路径成型，可修改平面、位置、比例及生成类型。':'Independent profile; edit its plane, position, scale and output type.'});
Object.assign(names,{quickModel:'快捷模型',multiHole:'多位置打孔',slot:'长圆槽',logo:'LOGO',faceHole:'面上打孔',faceExtrude:'面上拉伸',sweep:'扫掠',loft:'放样',split:'分割',extractSolid:'提取实体',section:'剖切'});
Object.assign(choiceNames,{relative:'相对位移',absolute:'绝对位置（包围盒中心）',engrave:'凹字 / 刻入',emboss:'凸字 / 浮雕'});
addTranslations({'LOGO':'Logo','LOGO 加工方式':'Logo operation','凹凸深度（核对尺寸）':'Depth (verify dimension)','LOGO 比例':'Logo scale','LOGO 旋转角':'Logo rotation','面内 X 偏移':'Face X offset','面内 Y 偏移':'Face Y offset','水平镜像':'Mirror horizontally','凹字 / 刻入':'Engrave / recessed','凸字 / 浮雕':'Emboss / raised','导入 LOGO 轮廓':'Import logo contours','选择 .logo.json':'Choose .logo.json','仅支持选中平面的凹凸加工；曲面环绕暂不支持。':'Engraving and embossing support planar faces only. Curved-surface wrapping is not supported.','请使用原 DWG 中经核对的闭合 LOGO 轮廓，不得用客户栏文字替代。':'Use verified closed logo contours from the original DWG, not text from the customer title-block field.','默认深度 0.2 mm 仅为示例，实际尺寸、比例与方向请在加工前核对。':'The default depth of 0.2 mm is an example. Verify actual dimensions, scale and orientation before applying.','请先导入有效的 .logo.json 文件。':'Import a valid .logo.json file first.','LOGO 文件必须为 .logo.json，且不超过 2 MB。':'Choose a .logo.json file no larger than 2 MB.','LOGO JSON 格式无效。':'Invalid logo JSON.','LOGO 文件须为 webcad-logo v1，单位 mm。':'The file must use webcad-logo v1 with mm units.','LOGO 缺少名称、来源或有效尺寸。':'The logo is missing its name, source or valid size.','LOGO 必须包含有效的闭合轮廓。':'The logo must contain valid closed contours.','LOGO 坐标必须是有限的二维数值，且闭合轮廓面积不能为零。':'Logo coordinates must be finite 2D numbers; closed contours must have nonzero area.','文件名':'File name','轮廓尺寸':'Contour dimensions','文件标注尺寸':'Declared dimensions','填充区域':'Filled regions','闭合轮廓数':'Closed contours','来源':'Source','仅显示导入轮廓；加工位置以三维预览为准。':'This view shows imported contours only. Use the 3D preview to verify placement.','在一个选定平面上导入闭合 LOGO 轮廓并凹刻或凸起':'Import closed logo contours to engrave or emboss on one selected planar face'});
addTranslations({'选择 .logo.json / SVG / DXF / DWG / PDF / AI':'Choose .logo.json / SVG / DXF / DWG / PDF / AI','识别轮廓 / Inspect':'Inspect contours','页码必须是大于等于 1 的整数。':'Page must be an integer of 1 or greater.','毫米 / native unit 必须为正数。':'Millimeters per native unit must be positive.','请输入有效的范围：xmax > xmin 且 ymax > ymin。':'Enter a valid range: xmax > xmin and ymax > ymin.','本机服务未提供 LOGO 转换接口（404）。请重启本机 WebCAD 服务；Vite 开发服务器不能转换这些文件。':'The local service has no LOGO conversion endpoint (404). Restart the local WebCAD service; the Vite dev server cannot convert these files.','本机 LOGO 转换失败':'Local logo conversion failed','本机服务返回了无效的轮廓识别结果。':'The local service returned invalid contour inspection data.','LOGO 源文件不能超过 20 MiB。':'Logo source files must be 20 MiB or smaller.','LOGO JSON 必须不超过 2 MiB。':'Logo JSON files must be 2 MiB or smaller.','无法读取所选本地文件。':'Could not read the selected local file.','请先识别矢量轮廓。':'Inspect vector contours first.','本机服务未返回可用的 LOGO 数据。':'The local service returned no usable logo data.','页码':'Page','选全部 / Select all':'Select all','提取所选轮廓 / Extract selection':'Extract selection','当前选区：—':'Selection: —'});
addTranslations({'保留原复合体':'Keep source compound','贯穿实体':'Through body','末截面半径':'End radius','末截面宽度':'End width','末截面深度':'End depth','末截面 X 偏移':'End X offset','末截面 Y 偏移':'End Y offset','分割平面':'Split plane','截面尺寸按字段定义。内尺寸、外尺寸和线径不同，请核对后生成。':'Dimensions follow the field definitions. Check inner dimensions, outer dimensions and section sizes before creating.','面操作需要先选择一个平面。':'Select a planar face before using face tools.','由两个平行 XY 截面生成实体。':'Create a solid between two parallel XY sections.','沿三维折线路径扫掠截面。路径转折过急或自交时可能失败。':'Sweep a profile along a 3D polyline. Sharp turns and self-intersections may fail.','分割保留平面两侧的实体，结果是一个复合体。':'Split keeps solids on both sides as a compound.','索引从 0 开始。可保留原复合体并提取副本，或仅保留指定实体；操作可撤销。':'Index starts at 0. Keep the source compound for a copy, or retain only the extracted solid. The operation can be undone.','视图剖切仅影响显示，不修改导出几何。':'View sectioning only changes the display, not exported geometry.'});
addTranslations({'长圆槽':'Capsule slot','槽总长':'Overall slot length','槽宽':'Slot width','切入深度':'Cut depth','切入轴':'Cut axis','切入方向':'Cut direction','槽旋转角':'Slot rotation','总长包含两端半圆；总长须不小于槽宽。起点是刀具入口中心。Z 轴长边沿 X，X 轴沿 Y，Y 轴沿 Z；角度绕正切入轴按右手旋转。':'Overall length includes both semicircles and must be at least the width. Start is the cutter entry center. Long direction: Z axis uses X, X uses Y, Y uses Z. Rotation follows the right-hand rule around the positive cut axis.'});
const symbols={box:'▱',cylinder:'▥',sphere:'◉',cone:'△',torus:'◎',extrude:'↥',revolve:'⟳',sketch:'✎',transform:'✥',copy:'⧉',mirror:'◧',union:'∪',cut:'−',intersect:'∩',fillet:'◜',chamfer:'◩',shell:'▣',hole:'⊙',multiHole:'⠿',slot:'⊖',linearPattern:'⋮',circularPattern:'⁙',remove:'⌫'};
Object.assign(names,{selectTool:'选择',group:'组合',explode:'拆散',gizmoTranslate:'移动手柄',gizmoRotate:'旋转手柄',gizmoOff:'关闭手柄'});
Object.assign(symbols,{group:'▣',explode:'▦',vectorProfile:'◇',logo:'Aa',quickModel:'▦',sweep:'↝',loft:'⋈',split:'◫',extractSolid:'▧',faceHole:'⊡',faceExtrude:'↦',gizmoTranslate:'✥',gizmoRotate:'⟲',gizmoOff:'⊗'});
function element(tag,attrs={},text){const el=document.createElement(tag);for(const [k,v]of Object.entries(attrs)){if(k==='class')el.className=v;else el.setAttribute(k,v);}if(text!==undefined)el.textContent=text;return el;}
function button(text,action,className=''){const b=element('button',{type:'button',class:className},text);b.addEventListener('click',action);return b;}
export function validateLogoDocument(data){
 if(!data||data.type!=='webcad-logo'||data.version!==1||data.units!=='mm')throw new Error('LOGO 文件须为 webcad-logo v1，单位 mm。');
 const dimensions=Array.isArray(data.sizeMm)?data.sizeMm:[data.sizeMm?.width,data.sizeMm?.height];
 if(typeof data.name!=='string'||!data.name.trim()||!data.source||!['string','object'].includes(typeof data.source)||dimensions.length!==2||dimensions.some(n=>typeof n!=='number'||!Number.isFinite(n)||n<=0))throw new Error('LOGO 缺少名称、来源或有效尺寸。');
 if(!Array.isArray(data.regions)||!data.regions.length)throw new Error('LOGO 必须包含有效的闭合轮廓。');
 const ring=points=>{if(!Array.isArray(points)||points.length<3||points.some(p=>!Array.isArray(p)||p.length!==2||p.some(n=>typeof n!=='number'||!Number.isFinite(n))))throw new Error('LOGO 坐标必须是有限的二维数值，且闭合轮廓面积不能为零。');let area=0;for(let i=0;i<points.length;i++){const a=points[i],b=points[(i+1)%points.length];area+=a[0]*b[1]-b[0]*a[1];}if(!Number.isFinite(area)||Math.abs(area)<1e-12)throw new Error('LOGO 坐标必须是有限的二维数值，且闭合轮廓面积不能为零。');return points.map(p=>[p[0],p[1]]);};
 const regions=data.regions.map(region=>{if(!region||!Array.isArray(region.holes??[]))throw new Error('LOGO 必须包含有效的闭合轮廓。');return {outer:ring(region.outer),holes:(region.holes||[]).map(ring)};});
 return {name:data.name.trim(),source:data.source,sizeMm:data.sizeMm,regions};
}
function logoSummary(logo){
 const box=element('div',{class:'logo-summary'}),info=element('dl',{class:'logo-facts'});let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity,loops=0;
 for(const region of logo.regions||[])for(const ring of [region.outer,...(region.holes||[])]){loops++;for(const [x,y]of ring){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);}}
 const width=maxX-minX,height=maxY-minY,declared=Array.isArray(logo.sizeMm)?logo.sizeMm:[logo.sizeMm?.width,logo.sizeMm?.height];
 for(const [label,value]of [['名称',logo.name||'LOGO'],['轮廓尺寸',`${width.toFixed(3)} × ${height.toFixed(3)} mm`],['文件标注尺寸',declared.every(Number.isFinite)?`${declared[0]} × ${declared[1]} mm`:'—'],['填充区域',String(logo.regions?.length||0)],['闭合轮廓数',String(loops)],['来源',typeof logo.source==='string'?logo.source:JSON.stringify(logo.source||{})]]){info.append(element('dt',{},label),element('dd',{'data-no-translate':''},value));}
 box.append(info);if(Number.isFinite(width)&&Number.isFinite(height)&&width>0&&height>0){const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg'),pad=Math.max(width,height)*.07;svg.setAttribute('class','logo-contour-preview');svg.setAttribute('viewBox',`${minX-pad} ${-maxY-pad} ${width+2*pad} ${height+2*pad}`);svg.setAttribute('role','img');svg.setAttribute('aria-label','LOGO');for(const region of logo.regions){const path=document.createElementNS(ns,'path');path.setAttribute('fill-rule','evenodd');path.setAttribute('d',[region.outer,...(region.holes||[])].map(points=>points.map(([x,y],i)=>`${i?'L':'M'}${x} ${-y}`).join(' ')+' Z').join(' '));svg.append(path);}box.append(svg,element('p',{class:'property-footnote'},'仅显示导入轮廓；加工位置以三维预览为准。'));}return box;
}
export function createUI(root,callbacks={}) {
 const state={document:{name:'未命名设计',features:[],hidden:[]},bodies:[],selectedIds:[],busy:false,kernelReady:false,snapEnabled:true};
 let activeCategory='编辑', propertyId=null,dialog=null,lastTreeKey='',lastPropKey='', previewActive=false;
 const translator=watchTranslations(root);
 const toolButtons=[];
 root.innerHTML=`<div class="webcad-app"><header class="app-header"><div class="brand"><span class="brand-mark">W</span><div>WebCAD<small>精确实体设计</small></div></div><button class="document-title" title="重命名工程"><span id="document-name">未命名设计</span><span class="title-edit">✎</span></button><div class="header-actions"></div><span class="local-badge"><i></i>本机计算 · 毫米</span></header><nav class="ribbon-tabs" aria-label="工具类别"><div class="tab-list" role="tablist" aria-label="工具类别"></div><div class="quick-history"></div></nav><section class="ribbon" aria-label="建模工具"></section><div class="selection-context"><span class="context-text" role="status"></span><button class="clear-selection" type="button">清除选择</button></div><main class="workspace"><aside class="left-panel"><div class="panel-heading"><span>设计树</span><span class="body-count">0 个实体</span></div><div class="document-tree"><div class="tree-title">实体 <span class="selection-hint">Ctrl 多选</span></div><div class="body-tree"></div><div class="tree-title history-title">建模历史 <span class="feature-count"></span></div><div class="feature-tree"></div></div><div class="sidebar-note">工程保存为 .webcad<br>可保留参数与完整建模历史</div></aside><section class="canvas-panel"><div class="viewport-topbar"><div class="selection-modes" aria-label="选择模式"></div><div class="view-actions"></div></div><div id="viewport"></div><div class="empty-state"><h1>开始设计</h1><p>从顶部菜单创建模型，或打开已有文件。</p><small>拖入文件以打开 · 单位 mm</small></div><div class="viewport-bottom"><span class="viewport-hint">左键选择 · 拖动旋转 · 滚轮缩放 · 右键平移</span><span class="view-label">透视视图</span></div><div class="busy-overlay" hidden><span class="spinner"></span><span class="busy-message">正在计算实体…</span></div></section><aside class="right-panel"><div class="panel-heading">属性 <span class="unit-pill">mm / °</span></div><div class="properties"></div></aside></main><footer class="statusbar"><span class="status-dot"></span><span class="status-message" role="status" aria-live="polite">正在初始化建模内核…</span><span class="status-detail"></span><span class="kernel-state">内核加载中</span></footer><div class="notification-area" aria-live="polite"></div></div>`;
 const app=root.querySelector('.webcad-app'),q=s=>root.querySelector(s);
 const finishControl=element('label',{class:'finish-control'});
 finishControl.append(element('span',{},'渲染'));
 const finishSelect=element('select',{'aria-label':'金属渲染',title:'全场景表面预览，选择后保持到下次打开'});
 for(const [key,preset] of Object.entries(METAL_FINISHES))finishSelect.append(element('option',{value:key},preset.label));
 finishSelect.addEventListener('change',()=>emit('metalFinish',{key:finishSelect.value}));
 finishControl.append(finishSelect);q('.viewport-topbar').insertBefore(finishControl,q('.view-actions'));
 async function emit(action,params){try{return await callbacks.onAction?.(action,params);}catch(e){api.showError(e.message||String(e));}}
 function closeDialog(cancelPreview=true){const shouldCancel=previewActive||dialog?.dataset.previewCapable==='true';dialog?.remove();dialog=null;if(cancelPreview&&shouldCancel){previewActive=false;emit('cancelPreview',{});}}
 function openDialog(title,description){closeDialog();dialog=element('dialog',{class:'cad-dialog'});const head=element('div',{class:'dialog-header'});const select=button('',activateSelectTool,'dialog-select');select.title='取消当前工具，返回箭头选择';select.setAttribute('aria-label','选择');select.dataset.action='selectTool';select.append(selectionIcon(),element('span',{},'选择'));head.append(element('h2',{},title),select,button('×',closeDialog,'close-button'));dialog.append(head);if(description)dialog.append(element('p',{class:'dialog-description'},description));root.append(dialog);dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});dialog.addEventListener('cancel',e=>{e.preventDefault();closeDialog();});dialog.showModal();return dialog;}
 function addBasicField(form,spec,value){const [key,label,def,kind]=spec,wrap=element('label',{class:'form-field','data-field':key});wrap.append(element('span',{},label));let input;if(Array.isArray(kind)){input=element('select',{name:key});kind.forEach(v=>input.append(element('option',{value:v},choiceNames[v]||v)));input.value=value??def;}else if(kind==='boolean'){input=element('input',{name:key,type:'checkbox'});input.checked=value??def;}else if(kind==='points'||kind==='points3'||kind==='holePoints3'){input=element('textarea',{name:key,rows:4,spellcheck:'false'});input.value=Array.isArray(value)?value.map(p=>p.join(',')).join('\n'):value??def;wrap.classList.add('wide');wrap.append(element('small',{},kind==='holePoints3'?'每行一组 X,Y,Z，共 1 至 100 个钻孔起点':kind==='points3'?'每行一组 X,Y,Z，至少两个点':'每行一组 X,Y，至少三个顶点'));}else{input=element('input',{name:key,type:'number',step:'any',required:''});input.value=value??def;if(kind==='positive')input.min='0.000001';if(kind==='integer'){input.min='0';input.step='1';}if(kind==='count'){input.min='2';input.max='100';input.step='1';}if(kind==='nonnegative')input.min='0';if(kind==='angle'){input.min='0.000001';input.max='360';}}wrap.append(input);form.append(wrap);return input;}
 function addField(form,spec,value){return addAdvancedField(form,spec,value,element)||addBasicField(form,spec,value);}
 function readParams(form,specs,base={}){return readAdvancedJson(form,specs,readBasicParams(form,specs.filter(spec=>spec[3]!=='json'),base));}
 function refreshProfile(form){const profile=form.elements.profile?.value;if(!profile)return;for(const k of ['width','depth','radius','endWidth','endDepth','endRadius','cornerRadius','startAngle','endAngle','closure']){const field=form.querySelector(`[data-field="${k}"]`);if(field){const enabled=['rectangle','roundedRectangle'].includes(profile)?(['width','depth','endWidth','endDepth'].includes(k)||(profile==='roundedRectangle'&&k==='cornerRadius')):['circle','arc'].includes(profile)?(['radius','endRadius'].includes(k)||(profile==='arc'&&['startAngle','endAngle','closure'].includes(k))):false;field.hidden=!enabled;field.querySelector('input,textarea,select').disabled=!enabled;}}const points=form.querySelector('[data-field="points"]');if(points&&points.querySelector('textarea')?.getAttribute('rows')==='4'&&!form.dataset.path){const enabled=profile==='polygon';points.hidden=!enabled;points.querySelector('textarea').disabled=!enabled;}}
 function readBasicParams(form,specs,base={}){const params={...base};for(const [key,,def,kind]of specs){const input=form.elements.namedItem(key);if(!input||input.disabled)continue;if(kind==='boolean'){params[key]=input.checked;}else if(Array.isArray(kind)){params[key]=key==='direction'?Number(input.value):input.value;}else if(kind==='points'||kind==='points3'||kind==='holePoints3'){const pts=input.value.trim().split(/[\n;]+/).map(row=>row.trim().split(/[,，\s]+/).map(Number));if(pts.length<(kind==='holePoints3'?1:kind==='points3'?2:3)||(kind==='holePoints3'&&pts.length>100)||pts.some(p=>p.length!==(kind==='points'?2:3)||p.some(v=>!Number.isFinite(v))))throw new Error(kind==='holePoints3'?'请输入 1 至 100 个有效的 X,Y,Z 钻孔起点。':kind==='points3'?'路径至少需要两个有效的 X,Y,Z 点。':'多边形请输入至少三个有效的 X,Y 顶点。');params[key]=pts;}else{const n=Number(input.value);if(!input.value.trim()||!Number.isFinite(n))throw new Error('请填写有效数值。');if(kind==='integer'&&(!Number.isInteger(n)||n<0))throw new Error('数量必须是非负整数。');if(kind==='count'&&(!Number.isInteger(n)||n<2||n>100))throw new Error('阵列数量必须为 2 至 100 的整数。');if(kind==='nonzero'&&n===0)throw new Error('拉伸高度不能为 0；负数表示反向拉伸。');if(kind==='positive'&&n<=0)throw new Error('尺寸必须大于 0。');if(kind==='nonnegative'&&n<0)throw new Error('该尺寸不能为负数。');if(kind==='angle'&&(n<=0||n>360))throw new Error('旋转角度应大于 0 且不超过 360°。');params[key]=n;}}if(params.majorRadius!==undefined&&params.minorRadius>=params.majorRadius)throw new Error('管半径必须小于主半径。');if(params.radius1===0&&params.radius2===0)throw new Error('圆锥至少一个半径应大于 0。');if(specs.some(([key])=>key==='pointX')){params.point=[params.pointX,params.pointY,params.pointZ];delete params.pointX;delete params.pointY;delete params.pointZ;}return params;}
 function configurePositionForm(form,body){const mode=form.elements.namedItem('positionMode');if(!mode)return;const update=(reset=false)=>{const absolute=mode.value==='absolute';['x','y','z'].forEach((key,i)=>{form.querySelector('[data-field="'+key+'"] span').textContent=t(absolute?['目标中心 X','目标中心 Y','目标中心 Z'][i]:['X 位移','Y 位移','Z 位移'][i]);if(reset)form.elements.namedItem(key).value=absolute?(body?.bounds?(body.bounds.min[i]+body.bounds.max[i])/2:''):0;});};mode.addEventListener('change',()=>update(true));update();}
 function actionDialog(action){const notes={box:'长方体从全局原点沿正 X、Y、Z 方向生成；创建后使用移动设置具体位置。',cylinder:'底面圆心位于全局原点，沿正 Z 方向生成；创建后使用移动设置具体位置。',cone:'底面圆心位于全局原点，沿正 Z 方向生成；创建后使用移动设置具体位置。',sphere:'球心位于全局原点；创建后使用移动设置具体位置。',torus:'圆环中心位于全局原点，轴向为 Z；创建后使用移动设置具体位置。',slot:'总长包含两端半圆；总长须不小于槽宽。起点是刀具入口中心。Z 轴长边沿 X，X 轴沿 Y，Y 轴沿 Z；角度绕正切入轴按右手旋转。',multiHole:'每个坐标是钻孔刀具的全局起点。所有孔沿指定轴方向切入；每个孔都必须实际去除材料，不生成螺纹。',faceHole:'先用鼠标点击平面的孔中心，再打开工具。下方显示点击位置的全局 X、Y、Z，可精确修改；孔中心必须位于所选平面内。先预览再确认。',faceExtrude:'面操作需要先选择一个平面。',sweep:'沿三维折线路径扫掠截面。路径转折过急或自交时可能失败。',loft:'由两个平行 XY 截面生成实体。',split:'平面位置是全局坐标：XY 对应 Z，XZ 对应 Y，YZ 对应 X。分割保留两侧实体，结果为复合体。',extractSolid:'索引从 0 开始。可保留原复合体并提取副本，或仅保留指定实体；操作可撤销。',section:'视图剖切仅影响显示，不修改导出几何。',hole:'从全局 X、Y、Z 起点沿指定轴方向钻孔，孔深单位 mm。钻孔圆柱必须与选中实体相交。',linearPattern:'沿每步位移复制选中实体。数量包含原件；阵列作为一个复合实体保存。',circularPattern:'围绕指定全局 X、Y、Z 轴心和轴方向复制实体。数量包含原件；360° 均匀环绕，部分角度包含起点与终点；结果作为一个复合实体保存。',transform:'相对位移：输入 X、Y、Z 移动量。绝对位置：将实体包围盒中心放到指定全局坐标。旋转和缩放以全局原点为基点；单位 mm / °。',copy:'保留原实体，并按全局 X、Y、Z 位移创建副本；旋转和缩放以全局原点为基点。',mirror:'沿经过全局原点的坐标平面镜像：YZ 为 X=0，XZ 为 Y=0，XY 为 Z=0；保留原实体。',fillet:'先切换到边并选择需要倒圆的边；如需整件处理，请明确勾选全部边。半径过大可能无法生成。',chamfer:'先切换到边并选择需要倒角的边；如需整件处理，请明确勾选全部边。',shell:'先切换到“面”，选择需要移除的面，再设定壁厚。',extrude:'选择预设轮廓或填写多边形顶点，也可以使用“绘制草图”。',revolve:'XY 平面轮廓绕全局 Y 轴旋转；XZ / YZ 平面轮廓绕全局 Z 轴旋转。距旋转轴为轮廓沿平面水平方向的偏移。'};
  const d=openDialog(names[action],advancedNotes[action]||notes[action]||'输入尺寸，创建可编辑的精确实体。'),form=element('form',{class:'parameter-form'});if(['sweep','multiHole','curveSweep'].includes(action))form.dataset.path='true';for(const f of fields[action]||[]){const axis=['pointX','pointY','pointZ'].indexOf(f[0]);addField(form,f,action==='faceHole'&&axis>=0?state.selectedTopology?.point?.[axis]:undefined);}if(action==='transform')configurePositionForm(form,state.bodies.find(b=>b.id===state.selectedIds[0]));bindParameterForm(form,action,()=>{const params=readParams(form,fields[action]||[]);if(['fillet','chamfer'].includes(action)&&!params.allEdges&&!(state.selectedTopology?.type==='edge'&&state.selectedTopology.ids?.length))throw new Error(t('请先选边，或明确勾选全部边。'));return params;},action!=='section');form.addEventListener('change',()=>refreshProfile(form));refreshProfile(form);d.append(form);form.querySelector('input,select')?.focus();}
 function logoDialog(action='logo'){
  const curved=action==='curvedLogo',specs=fields[action];
  const d=openDialog('导入 LOGO 轮廓',curved?advancedNotes.curvedLogo:'仅支持选中平面的凹凸加工；曲面环绕请使用曲面 LOGO。'),notice=element('p',{class:'logo-source-notice'},'请使用经核对的闭合 LOGO 轮廓，不得用客户栏文字替代。'),form=element('form',{class:'parameter-form'});let base=null;
  const importer=createLogoImportUI({validateLogoDocument,logoSummary,onLogo(logo){base=logo;form.dispatchEvent(new Event('input',{bubbles:true}));},async onInvalidate(){base=null;form.dispatchEvent(new Event('input',{bubbles:true}));previewActive=false;await emit('cancelPreview',{});}});
  d.append(element('p',{class:'dialog-description'},curved?'先选面并点击 LOGO 中心。正交投影到选中曲面，再沿局部法向等深凹刻；暂不支持跨面、接缝、凸字或拔模。':'默认脱模斜度 7°，0° 为直壁；承载面处轮廓保持原尺寸。'),notice,importer);
  specs.forEach(spec=>{const axis=['pointX','pointY','pointZ'].indexOf(spec[0]);addField(form,spec,curved&&axis>=0?state.selectedTopology?.point?.[axis]:undefined);});
  bindParameterForm(form,action,()=>{if(!base)throw new Error('请先导入有效的 LOGO 文件。');return readParams(form,specs,curved?{...base,mode:'engrave',draftAngle:0}:base);});d.append(form);
 }
 function configureVectorForm(form){const update=()=>{const face=form.elements.namedItem('output').value==='face',height=form.querySelector('[data-field="height"]');height.hidden=face;height.querySelector('input').disabled=face;};form.elements.namedItem('output').addEventListener('change',update);update();}
 function vectorProfileDialog(){
  const d=openDialog('导入路径','导入或粘贴闭合矢量路径，直接生成面或实体。轮廓包围盒中心放置于指定全局 XYZ；平面内缩放和旋转围绕此中心。'),form=element('form',{class:'parameter-form'});let base=null;
  const importer=createLogoImportUI({validateLogoDocument,logoSummary,onLogo(logo){base=logo;form.dispatchEvent(new Event('input',{bubbles:true}));},async onInvalidate(){base=null;form.dispatchEvent(new Event('input',{bubbles:true}));previewActive=false;await emit('cancelPreview',{});}});
  fields.vectorProfile.forEach(spec=>addField(form,spec));configureVectorForm(form);bindParameterForm(form,'vectorProfile',()=>{if(!base)throw new Error(t('请先导入或粘贴有效的闭合路径。'));return readParams(form,fields.vectorProfile,{regions:base.regions,source:base.source});});d.append(importer,element('p',{class:'property-footnote'},'正高度方向 / Positive height: XY → +Z；XZ → −Y；YZ → +X。负高度反向 / Negative height reverses direction.'),form);
 }
 function bindParameterForm(form,op,read,preview=true){
  form.append(createDimensionCalculator(form,{element,button}));
  if(preview&&dialog)dialog.dataset.previewCapable='true';
  const error=element('p',{class:'form-error wide',role:'alert'}),hint=element('p',{class:'preview-hint wide'}),foot=element('div',{class:'dialog-footer wide'}),submit=element('button',{type:'submit',class:'primary'},'确定');
  let ready=false,working=false;const apply=button('应用预览',async()=>{if(!ready||working)return;working=true;apply.disabled=true;try{const result=await callbacks.onAction?.('commitPreview',{});if(result!==false){previewActive=false;closeDialog(false);}}catch(e){error.textContent=e.message;}finally{working=false;apply.disabled=!ready;}},'primary');apply.disabled=true;
  apply.hidden=true;if(preview){const previewButton=button('预览',async()=>{if(working||!form.reportValidity())return;working=true;previewButton.disabled=true;error.textContent='';try{const params=read();const result=await callbacks.onAction?.('preview',{op,params});if(result===false){ready=false;return;}if(!form.isConnected){await callbacks.onAction?.('cancelPreview',{});previewActive=false;return;}previewActive=true;ready=true;apply.hidden=false;apply.disabled=false;hint.textContent='预览已生成，可调整参数重新预览或应用。';dialog?.classList.add('preview-dialog');}catch(e){error.textContent=e.message;ready=false;}finally{working=false;previewButton.disabled=false;apply.disabled=!ready;}},'secondary');foot.append(previewButton,apply);}
  foot.append(button('取消',()=>closeDialog(),'secondary'),submit);form.append(error,hint,foot);form.addEventListener('input',()=>{ready=false;apply.hidden=true;apply.disabled=true;hint.textContent=previewActive?'请先预览当前参数。':'';});form.addEventListener('submit',async e=>{e.preventDefault();if(working)return;try{const params=read();if(previewActive){const result=await callbacks.onAction?.('cancelPreview',{});if(result===false)return;previewActive=false;}working=true;submit.disabled=true;const result=await callbacks.onAction?.(op,params);if(result!==false)closeDialog(false);else error.textContent=q('.status-message').textContent;}catch(ex){error.textContent=ex.message;}finally{working=false;submit.disabled=false;}});
 }
 function quickSpecs(kind){const model=QUICK_MODELS[kind];if(!model)return[];addTranslations({[model.label]:model.labelEn||model.label,...(model.descriptionEn?{[model.description]:model.descriptionEn}:{})});return model.fields.map(field=>{addTranslations({[field.label]:field.labelEn||field.label});if(field.options)for(const o of field.options){choiceNames[o.value]=o.label;addTranslations({[o.label]:o.labelEn||o.label});}return [field.key,field.label,model.defaults[field.key],field.type==='select'?field.options.map(o=>o.value):field.min>0?'positive':field.min===0?'nonnegative':undefined];});}
 function quickModelDialog(){const d=openDialog('快捷模型','截面尺寸按字段定义。内尺寸、外尺寸和线径不同，请核对后生成。'),picker=element('select',{'aria-label':'快捷模型',class:'quick-model-picker'});for(const [kind,model]of Object.entries(QUICK_MODELS)){quickSpecs(kind);picker.append(element('option',{value:kind},model.label));}const host=element('div');const render=()=>{host.replaceChildren();const model=QUICK_MODELS[picker.value],description=element('p',{class:'dialog-description'},getLanguage()==='en'?(model.descriptionEn||model.description):model.description),form=element('form',{class:'parameter-form'}),specs=quickSpecs(picker.value);for(const spec of specs){const input=addField(form,spec);const field=model.fields.find(f=>f.key===spec[0]);for(const key of ['min','max','step'])if(field[key]!==undefined)input.setAttribute(key,field[key]);}bindParameterForm(form,'quickModel',()=>({...model.defaults,...readParams(form,specs),kind:picker.value}));host.append(description,form);};picker.addEventListener('change',async()=>{if(previewActive){await emit('cancelPreview',{});previewActive=false;}render();});d.append(picker,host);render();}
 function sketchDialog(){const d=openDialog('绘制草图','选择预设轮廓或交互绘制。水平/垂直吸附是绘制辅助，不是完整约束求解器。'),form=element('form',{class:'parameter-form'});const specs=[['preset','绘制方式','polygon',['polygon','line','rectangle','circle','roundedRectangle','arc']],['snapHV','水平 / 垂直吸附',true,'boolean'],['snap','网格吸附',true,'boolean'],['width','宽度',30,'positive'],['depth','深度',20,'positive'],['radius','半径',10,'positive'],['cornerRadius','外轮廓圆角',3,'nonnegative'],['startAngle','起始角',0],['endAngle','结束角',90],['closure','封闭方式','sector',['sector','segment']],['height','拉伸高度（负数反向）',5,'nonzero']];Object.assign(choiceNames,{line:'折线轮廓',roundedRectangle:'圆角矩形',arc:'圆弧',sector:'扇形',segment:'弓形',polygon:'多边形'});specs.forEach(spec=>addField(form,spec));const refresh=()=>{const preset=form.elements.preset.value;for(const [key]of specs){const keep=key==='preset'||(['snapHV','snap'].includes(key)&&['polygon','line'].includes(preset))||(['width','depth'].includes(key)&&['rectangle','roundedRectangle'].includes(preset))||(key==='cornerRadius'&&preset==='roundedRectangle')||(key==='radius'&&['circle','arc'].includes(preset))||(['startAngle','endAngle','closure'].includes(key)&&preset==='arc')||(key==='height'&&!['polygon','line'].includes(preset));const wrapper=form.querySelector(`[data-field="${key}"]`);wrapper.hidden=!keep;form.elements[key].disabled=!keep;}};form.addEventListener('change',refresh);refresh();bindParameterForm(form,'sketch',()=>readParams(form,specs),false);d.append(form);}
 async function activateSelectTool(){const cancel=previewActive||dialog?.dataset.previewCapable==='true';closeDialog(false);previewActive=false;if(cancel)await emit('cancelPreview',{});return emit('selectTool');}
 function selectionIcon(){const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg'),path=document.createElementNS(ns,'path');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('class','selection-arrow');svg.setAttribute('aria-hidden','true');path.setAttribute('d','M5 3 L5 19 L9.5 14.5 L13 22 L16 20.5 L12.5 13 L19 13 Z');svg.append(path);return svg;}
 function run(action){if(action==='selectTool')return activateSelectTool();if(action==='vectorProfile')return vectorProfileDialog();if(['logo','curvedLogo'].includes(action))return logoDialog(action);if(action==='gizmoTranslate'||action==='gizmoRotate')return emit('gizmo',{mode:action==='gizmoTranslate'?'translate':'rotate'});if(action==='gizmoOff')return emit('gizmo',{mode:'off'});if(action==='quickModel')return quickModelDialog();if(action==='sketch')return sketchDialog();if(fields[action])return actionDialog(action);if(action==='export')return exportDialog();if(action==='help')return helpDialog();if(action==='remove'){if(!state.selectedIds.length)return;const d=openDialog('删除选中实体','此操作保留在建模历史中，可以撤销。');const foot=element('div',{class:'dialog-footer'});foot.append(button('取消',closeDialog,'secondary'),button('删除实体',()=>{closeDialog();emit('remove');},'danger'));d.append(foot);return;}emit(action);}
 function exportDialog(){const d=openDialog('导出模型','选择交换格式。若要继续修改参数，请同时保存 WebCAD 工程。');const form=element('form');for(const [value,title,description]of [['step','STEP / STP','精确实体 · 用于 Creo、SolidWorks、Fusion 等 CAD'],['stl','STL','三角网格 · 用于切片与 3D 打印，不保留精确曲面'],['brep','BREP','OpenCascade 原生精确几何']]){const label=element('label',{class:'export-option'}),input=element('input',{type:'radio',name:'format',value});input.checked=value==='step';const text=element('div');text.append(element('strong',{},title),element('small',{},description));label.append(input,text);form.append(label);}const scope=element('label',{class:'checkbox-field'}),check=element('input',{type:'checkbox',name:'selected'});check.disabled=!state.selectedIds.length;scope.append(check,document.createTextNode(`仅导出选中实体（${state.selectedIds.length}）`));form.append(scope);const foot=element('div',{class:'dialog-footer'});foot.append(button('取消',closeDialog,'secondary'),element('button',{type:'submit',class:'primary'},'导出文件'));form.append(foot);form.addEventListener('submit',e=>{e.preventDefault();const params={format:form.elements.format.value,selected:check.checked};closeDialog();emit('export',params);});d.append(form);}
 function helpDialog(){api.showInfo('WebCAD 使用指南','1. 新建：使用工具栏创建实体，或“绘制草图”后拉伸。\n2. 编辑：选中实体，在右侧修改生成参数；历史条目也可编辑。\n3. 布尔：按 Ctrl 依次选择两个实体，再合并、相减或相交。相减会从第一个实体减去后选实体。\n4. 圆角 / 倒角：切换“边”并选择边；要处理整件须明确勾选全部边。\n5. 视图：左键拖动旋转，滚轮缩放，右键拖动平移。\n6. 保存工程可保留参数和导入源文件；STEP 用于 CAD 交换，STL 用于 3D 打印。\n7. 导入 STEP 可以继续加工，但不能恢复其他 CAD 软件的原始特征树。\n8. 快捷模型新增扁平框和安装板；尺寸按模板字段定义，安装板孔由参数生成。\n9. 多位置打孔：先选择实体，再输入 1 至 100 个全局钻孔起点；共享孔半径、深度及轴向，不生成螺纹。\n\n所有几何计算在本机浏览器进行。尺寸单位：毫米；角度单位：度。');const viewer=element('div',{class:'property-footnote'});viewer.append(element('a',{href:'./automation/index.md',target:'_blank',rel:'noopener noreferrer'},'页面 API 工具目录'),element('p',{},'读取工具卡、参数单位与限制；静态版不含 IGES 或服务端矢量转换器。'));viewer.append(button('自动化接口',mcpDialog,'secondary'));dialog.querySelector('.info-content').append(viewer);}
 function examplesDialog(){const d=openDialog('打开示例工程','选择一个可编辑的实体工程，查看建模历史并修改尺寸。'),list=element('div');for(const [name,label,description]of [['mounting-bracket','带孔安装支架','板件、安装孔与支撑结构'],['buckle-frame','圆角扣框','扣框轮廓与圆角加工'],['open-box','薄壁盒','盒体与壁厚设计']]){const b=button('',()=>{closeDialog();emit('example',{name});},'export-option');b.style.width='100%';b.style.textAlign='left';const text=element('div');text.append(element('strong',{},label),element('small',{},description));b.append(text);list.append(b);}d.append(list);}
 const header=q('.header-actions');for(const [label,action,cls]of [['新建','new',''],['打开','open',''],['保存工程','save',''],['导出','export','primary']]){const b=button(label,()=>run(action),cls);b.dataset.action=action;header.append(b);}const exampleButton=button('示例',examplesDialog);exampleButton.dataset.action='example';header.append(exampleButton,button('帮助',()=>run('help'),'help-button'));
 const languageSelect=element('select',{class:'language-select','aria-label':'Language / 语言','data-no-translate':''});languageSelect.append(element('option',{value:'zh'},'中文'),element('option',{value:'en'},'English'));languageSelect.value=getLanguage();languageSelect.addEventListener('change',()=>{setLanguage(languageSelect.value);translator.translate();emit('language',{language:getLanguage()});});header.append(languageSelect);
 function parametersDialog(){
  const values=window.webcad.api.getState(),d=openDialog('命名参数','数值使用所选单位；表达式直接引用参数名，例如 length-edgeMargin。一次应用是一个可撤销动作。');
  const form=element('form',{'data-parameter-form':''}),table=element('div',{class:'property-grid'}),rows=[];
  function row(name='',definition={value:'',unit:'mm'}){
    const line=element('div',{class:'parameter-row'}),n=element('input',{placeholder:'参数名',value:name,'aria-label':'参数名'}),v=element('input',{value:String(definition.value),name:name||'newParameter','aria-label':name||'参数值'}),u=element('select',{'aria-label':'单位'});
    for(const unit of ['mm','scalar'])u.append(element('option',{value:unit},unit));u.value=definition.unit;
    line.append(n,v,u);table.append(line);rows.push({n,v,u});
  }
  for(const[name,definition]of Object.entries(values.parameters))row(name,definition);
  row();const error=element('p',{role:'alert'}),apply=button('应用参数',null,'primary');apply.type='submit';
  form.append(table,error,apply);form.onsubmit=async event=>{event.preventDefault();const parameters={};for(const{n,v,u}of rows){if(!n.value.trim())continue;const text=v.value.trim();parameters[n.value.trim()]={value:/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i.test(text)?Number(text):text,unit:u.value};}
    apply.disabled=true;try{const result=await callbacks.onAction('parameters',{parameters});if(result!==false)closeDialog();else error.textContent='参数更新失败，原工程保留。';}catch(e){error.textContent=e.message;}finally{apply.disabled=false;}};
  d.append(form);const bindings=element('pre',{},values.features.filter(f=>f.expressions).map(f=>f.name+': '+JSON.stringify(f.expressions)).join('\n'));d.append(bindings);
 }
 q('.statusbar').insertBefore(button('参数表',parametersDialog,'secondary'),q('.kernel-state'));
 const aiBadge=button('AI · 未连接',()=>mcpDialog(),'ai-status');q('.statusbar').insertBefore(aiBadge,q('.kernel-state'));
 function updateAI(){aiBadge.textContent='页面 API · r'+(state.revision??0);aiBadge.title='自动化接口';aiBadge.dataset.state='connected';}
 function mcpDialog(){const a=window.webcad?.api;api.showInfo('自动化接口','入口：window.webcad.api\n先 info() / getState()，再 searchTools({query:…}) / getTool({id:…})，按工具卡 execute。\n静态浏览器内核；侧边栏必须自行具备页面 JS 执行权限。\n'+JSON.stringify(a?.info(),null,2)+'\n'+(a?.readDocs({docId:'start'})?.text||''));}
 q('.document-title').addEventListener('click',()=>{const d=openDialog('重命名工程'),form=element('form'),input=element('input',{type:'text',required:'',maxlength:'100',class:'rename-input'});input.value=state.document?.name||'未命名设计';const foot=element('div',{class:'dialog-footer'});foot.append(button('取消',closeDialog,'secondary'),element('button',{type:'submit',class:'primary'},'保存'));form.append(input,foot);form.addEventListener('submit',e=>{e.preventDefault();const name=input.value.trim();if(name){callbacks.onRename?.(name);closeDialog();}});d.append(form);input.focus();input.select();});
 const categories={编辑:[['选择',['selectTool']],['变换与复制',['transform','copy','mirror']],['组合与拆散',['group','explode']],['交互手柄',['gizmoTranslate','gizmoRotate','gizmoOff']],['阵列',['linearPattern','circularPattern']],['管理',['remove']]],创建:[['基本实体',['box','cylinder','sphere','cone','torus']],['轮廓成型',['sketch','vectorProfile','extrude','revolve','sweep','loft','curveSweep','advancedLoft','fittedSurface']],['快捷模型',['quickModel']]],加工:[['布尔运算',['union','cut','intersect']],['孔与槽',['hole','multiHole','slot']],['面与边',['faceHole','faceExtrude','logo','curvedLogo','thickenFace','fillet','chamfer','shell']],['拆分',['split','extractSolid']]],视图:[]};
 const toolHelp={selectTool:'取消当前工具，返回箭头选择',group:'将选中实体组合为复合体，保持各实体独立，不做布尔合并',explode:'将复合体中的实体拆成可独立选择和编辑的对象；单一实体请先分割',logo:'在一个选定平面上导入闭合 LOGO 轮廓并凹刻或凸起',cut:'相减顺序：先选保留主体，再选切除刀具',shell:'选面后移除开口面并生成壁厚',fillet:'选择指定边，或明确勾选全部边',chamfer:'选择指定边，或明确勾选全部边',sketch:'绘制闭合轮廓，随后拉伸成实体',faceHole:'在选定平面上向实体内部打孔',faceExtrude:'沿选定平面的法向增加或切除材料'};
 categories.创建.push(['参考曲线',['planeSection','faceBoundary']]);
 categories.加工.push(['曲面处理',['sewFaces','surfaceTrim']]);
 function group(label){const g=element('div',{class:'ribbon-group'}),row=element('div',{class:'ribbon-tools'});g.append(row,element('div',{class:'ribbon-group-label'},label));q('.ribbon').append(g);return row;}
 function renderRibbon(){
  q('.ribbon').replaceChildren();toolButtons.length=0;
  for(const tab of q('.tab-list').children){const active=tab.dataset.category===activeCategory;tab.classList.toggle('active',active);tab.setAttribute('aria-selected',String(active));tab.tabIndex=active?0:-1;}
  if(activeCategory==='视图'){
   const views=group('标准视角');views.classList.add('view-grid');
   for(const [label,direction]of [['等轴','iso'],['前视','front'],['后视','back'],['俯视','top'],['仰视','bottom'],['左视','left'],['右视','right']])views.append(button(label,()=>emit('view',{direction}),'view-tool'));
   const display=group('显示方式');display.classList.add('view-grid');
   for(const [label,mode]of [['实体','solid'],['实体 + 边线','edges'],['线框','wire']]){const b=button(label,()=>emit('display',{mode}),'view-tool');b.dataset.setting='display';b.dataset.value=mode;display.append(b);}
   const projection=group('投影');projection.classList.add('view-stack');
   for(const [label,mode]of [['透视','perspective'],['正交','orthographic']]){const b=button(label,()=>emit('projection',{mode}),'view-tool');b.dataset.setting='projection';b.dataset.value=mode;projection.append(b);}
   const assists=group('显示辅助');assists.classList.add('view-grid');
   for(const [label,action,setting]of [['网格','grid','grid'],['几何吸附','snap','snap']]){const b=button(label,()=>emit(action),'view-tool');b.dataset.setting=setting;b.dataset.value='true';assists.append(b);}
   for(const [label,action]of [['适合窗口','fit'],['测量','measure'],['剖切','section'],['截图','screenshot']]){const b=button(label,()=>run(action),'view-tool');b.dataset.action=action;assists.append(b);toolButtons.push(b);}
  }else for(const [label,actions]of categories[activeCategory]){const row=group(label);for(const action of actions){const b=button('',()=>run(action),'tool-button');b.dataset.action=action;b.append(action==='selectTool'?selectionIcon():element('span',{class:'tool-icon','aria-hidden':'true'},symbols[action]||'◇'),element('span',{},names[action]||'绘制草图'));row.append(b);toolButtons.push(b);}}
  updateDisabled();updateViewControls();
 }
 for(const cat of Object.keys(categories)){const tab=button(cat,()=>{activeCategory=cat;renderRibbon();},'ribbon-tab');tab.dataset.category=cat;tab.setAttribute('role','tab');tab.addEventListener('keydown',e=>{const tabs=[...q('.tab-list').children],i=tabs.indexOf(tab);if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[next].click();tabs[next].focus();}});q('.tab-list').append(tab);}
 function updateViewControls(){const view=state.viewState||{display:'edges',projection:'perspective',grid:true,snap:true,gizmo:'off',selection:'body'};for(const b of q('.ribbon').querySelectorAll('[data-setting]')){const active=String(view[b.dataset.setting])===b.dataset.value;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));}for(const b of q('.selection-modes').children){const active=b.dataset.action==='selectTool'?view.selection==='body'&&view.gizmo==='off'&&!state.interactionMode:b.dataset.mode===view.selection;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));}for(const [action,mode]of [['gizmoTranslate','translate'],['gizmoRotate','rotate'],['gizmoOff','off']]){const b=q('.ribbon [data-action="'+action+'"]');if(b){b.classList.toggle('active',view.gizmo===mode);b.setAttribute('aria-pressed',String(view.gizmo===mode));}}const arrow=q('.ribbon [data-action="selectTool"]');if(arrow){const active=view.selection==='body'&&view.gizmo==='off'&&!state.interactionMode;arrow.classList.toggle('active',active);arrow.setAttribute('aria-pressed',String(active));}q('.view-label').textContent=view.projection==='orthographic'?'正交视图':'透视视图';}
 const selectTool=button('',activateSelectTool);selectTool.append(selectionIcon(),element('span',{},'选择'));selectTool.dataset.action='selectTool';selectTool.title='取消当前工具，返回箭头选择';q('.selection-modes').append(selectTool);const moveTool=button('移动',()=>run('transform'));moveTool.dataset.action='transform';q('.view-actions').append(moveTool);
 const undo=button('↶ 撤销',()=>emit('undo')),redo=button('↷ 重做',()=>emit('redo'));undo.title='Ctrl + Z';redo.title='Ctrl + Shift + Z';q('.quick-history').append(undo,redo);
 for(const [label,mode]of [['实体','body'],['面','face'],['边','edge']]){const b=button(label,()=>{q('.selection-modes').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));emit('selectMode',{mode});});b.dataset.mode=mode;if(mode==='body')b.classList.add('active');q('.selection-modes').append(b);}
 for(const [label,action]of [['⌂ 适合窗口','fit'],['测量','measure']]){const b=button(label,()=>emit(action));b.dataset.action=action;q('.view-actions').append(b);};
 
 function updateDisabled(){
  for(const b of toolButtons){const action=b.dataset.action,reason=toolDisabledReason(action,state);b.disabled=!!reason;b.title=reason||toolHelp[action]||names[action]||b.textContent;}
  undo.disabled=state.busy||!state.undoAvailable;redo.disabled=state.busy||!state.redoAvailable;
  for(const b of header.querySelectorAll('[data-action]'))b.disabled=state.busy||(b.dataset.action==='export'&&(!state.kernelReady||!state.bodies.length));

  q('.document-title').disabled=state.busy;selectTool.disabled=false;
  for(const b of q('.view-actions').children){b.disabled=!!toolDisabledReason(b.dataset.action,state);}
  const count=state.selectedIds.length,top=state.selectedTopology;
  let hint=!state.kernelReady?'建模内核尚未就绪':!state.bodies.length?'从快捷模型、基本实体或打开 STEP 开始':!count?'选择实体后可加工；Ctrl / Shift 多选':count>1?'已选多个实体：可进行布尔运算或删除；其他加工请只选一个':top?.ids?.length?top.type==='face'?'已选面：可打孔、面拉伸或抽壳':'已选边：圆角和倒角仅处理这些边':'已选一个实体：可加工、变换或编辑参数';
  if(count>1)hint+=' · '+state.selectedIds.map((id,i)=>(i+1)+'. '+(state.bodies.find(b=>b.id===id)?.name||id)).join(' → ');
  q('.context-text').textContent=hint;q('.clear-selection').disabled=!count||state.busy;
 }
 q('.clear-selection').addEventListener('click',()=>{propertyId=null;callbacks.onSelection?.(null);});
 function renderTrees(){const key=JSON.stringify([state.document?.features?.map(f=>[f.id,f.name,f.op]),state.document?.hidden,state.bodies.map(b=>[b.id,b.name]),state.selectedIds]);if(key===lastTreeKey)return;lastTreeKey=key;const bodies=q('.body-tree'),features=q('.feature-tree');bodies.replaceChildren();features.replaceChildren();q('.body-count').textContent=`${state.bodies.length} 个实体`;q('.feature-count').textContent=state.document?.features?.length||0;for(const body of state.bodies){const row=element('div',{class:`tree-row ${state.selectedIds.includes(body.id)?'selected':''}`});const pick=button('',()=>{},'tree-pick');pick.append(element('span',{class:'body-symbol'},'◇'),element('span',{class:'tree-name'},body.name||body.id));pick.addEventListener('click',e=>{propertyId=null;callbacks.onSelection?.(body.id,e.ctrlKey||e.metaKey||e.shiftKey);});const hidden=state.document?.hidden?.includes(body.id),eye=button(hidden?'○':'●',()=>callbacks.onVisibility?.(body.id),'visibility-button');eye.title=hidden?'显示实体':'隐藏实体';eye.setAttribute('aria-label',eye.title);row.append(pick,eye);bodies.append(row);}if(!state.bodies.length)bodies.append(element('div',{class:'tree-empty'},'尚无实体'));
 for(const [index,f]of (state.document?.features||[]).entries()){const b=button('',()=>{propertyId=f.id;lastPropKey='';renderProperties();},'feature-row');b.append(element('span',{class:'feature-index'},String(index+1).padStart(2,'0')),element('span',{class:'tree-name'},f.name||names[f.op]||f.op));b.dataset.featureId=f.id;b.title='编辑此步骤的参数';features.append(b);}if(!state.document?.features?.length)features.append(element('div',{class:'tree-empty'},'创建操作后显示历史'));}
 function renderProperties(explicitFeature,explicitBody){const f=explicitFeature||state.document?.features?.find(f=>f.id===(propertyId||state.selectedIds[0])),body=explicitBody||state.bodies.find(b=>b.id===(f?.id||state.selectedIds[0]));const key=JSON.stringify([f,body?.id,body?.bounds,body?.volume,state.selectedTopology,state.selectedIds,state.busy,state.document?.appearance,state.metalFinish]);if(key===lastPropKey)return;lastPropKey=key;const area=q('.properties');area.replaceChildren();area.scrollTop=0;for(const row of q('.feature-tree').children)row.classList.toggle('selected',row.dataset.featureId===(propertyId||state.selectedIds[0]));if(!f&&!body){const empty=element('div',{class:'property-empty'});empty.append(element('div',{class:'property-icon'},'⌖'),element('strong',{},'选择一个实体'),element('p',{},'查看尺寸与体积，修改参数或进行实体加工。'),element('small',{},'按 Ctrl 多选进行布尔运算'));area.append(empty);return;}area.append(element('h3',{class:'property-title'},f?.name||body?.name||'实体'));if(state.selectedIds.length>1)area.append(element('div',{class:'property-callout'},`已选择 ${state.selectedIds.length} 个实体。相减顺序以选择顺序为准。`));if(state.selectedTopology)area.append(element('p',{class:'topology-detail'},topologyLabel(state.selectedTopology)));
 const details=element('details',{class:'property-details',open:''});details.append(element('summary',{},'外观与尺寸'));if(body){const materialLabel=element('label',{class:'form-field part-finish'});materialLabel.append(element('span',{},'选中材质'));const materialSelect=element('select',{'aria-label':'选中材质'});for(const [key,preset]of Object.entries(METAL_FINISHES))materialSelect.append(element('option',{value:key},preset.label));materialSelect.value=state.document?.appearance?.[body.id]||state.metalFinish||Object.keys(METAL_FINISHES)[0];const applyMaterial=button('应用到选中',()=>emit('perPartMetal',{key:materialSelect.value}),'secondary');applyMaterial.disabled=!state.selectedIds.length||state.busy;materialLabel.append(materialSelect,applyMaterial);details.append(materialLabel);}if(body?.bounds){const dims=body.bounds.max.map((v,i)=>v-body.bounds.min[i]);const stats=element('div',{class:'geometry-stats'});[['实测 X',dims[0]],['实测 Y',dims[1]],['实测 Z',dims[2]],['实测体积',body.volume]].forEach(([label,value])=>{if(value!=null){const row=element('div');row.append(element('span',{},label),element('strong',{},`${Number(value).toLocaleString('zh-CN',{maximumFractionDigits:3})} ${label==='实测体积'?'mm³':'mm'}`));stats.append(row);}});details.append(stats);}
 if(propertyId)area.append(element('p',{class:'property-callout'},'正在编辑历史步骤；应用后会重建后续模型'));if(f){area.append(element('div',{class:'section-label'},`${names[f.op]||f.op} · 参数`));const specs=f.op==='quickModel'?quickSpecs(f.params?.kind):fields[f.op]||[],form=element('form',{class:'property-form'}),nameLabel=element('label',{class:'form-field'});nameLabel.append(element('span',{},'名称'));const nameInput=element('input',{name:'featureName',type:'text',required:'',maxlength:'100'});nameInput.value=f.name||names[f.op]||f.op;nameLabel.append(nameInput);form.append(nameLabel);if(['logo','curvedLogo','vectorProfile'].includes(f.op)&&f.params?.regions){area.append(logoSummary(f.params));area.append(element('p',{class:'property-footnote'},f.op==='vectorProfile'?'独立路径成型，可修改平面、位置、比例及生成类型。':f.op==='curvedLogo'?advancedNotes.curvedLogo:'仅支持选中平面的凹凸加工。'));}if(['sweep','multiHole','curveSweep'].includes(f.op))form.dataset.path='true';specs.forEach(spec=>{const axis=['pointX','pointY','pointZ'].indexOf(spec[0]);const value=f.op==='logo'&&spec[0]==='draftAngle'?(f.params?.draftAngle??0):['faceHole','curvedLogo'].includes(f.op)&&axis>=0?f.params?.point?.[axis]:spec[0]==='allEdges'?(f.params?.allEdges??!f.params?.edgeIds?.length):f.params?.[spec[0]];addField(form,spec,value);});if(f.op==='transform')configurePositionForm(form);if(f.op==='vectorProfile')configureVectorForm(form);refreshProfile(form);form.addEventListener('change',()=>refreshProfile(form));const error=element('p',{class:'form-error',role:'alert'}),submit=element('button',{type:'submit',class:'primary apply-button'},'应用参数');submit.disabled=state.busy;form.append(error,submit);form.addEventListener('submit',async e=>{e.preventDefault();try{const p=readParams(form,specs,f.params);submit.disabled=true;await callbacks.onEditFeature?.(f.id,p,nameInput.value.trim());}catch(ex){error.textContent=ex.message;}finally{submit.disabled=state.busy;}});area.append(form);if(f.op==='import')area.append(element('p',{class:'property-footnote'},'导入几何保留精确形状。可使用工具栏继续移动、布尔、倒角等加工；不包含原软件特征树。'));}if(body)area.append(details);}
 function topologyLabel(t){if(Array.isArray(t))return t.map(topologyLabel).join(' · ');if(typeof t!=='object')return String(t);const type=t.type||t.mode||'';if(t.ids?.length)return '已选'+(type==='edge'?'边':type==='face'?'面':type)+'：'+t.ids.join(', ');if(t.edgeIds?.length)return `已选边：${t.edgeIds.join(', ')}`;if(t.faceIds?.length)return `已选面：${t.faceIds.join(', ')}`;return `拓扑选择：${type==='edge'?'边':type==='face'?'面':type} ${t.edgeId??t.faceId??t.index??''}`;}
 const api={update(patch={}){if(patch.selectedIds && JSON.stringify(patch.selectedIds)!==JSON.stringify(state.selectedIds))propertyId=null;Object.assign(state,patch);if(patch.language){setLanguage(patch.language);languageSelect.value=getLanguage();translator.translate();}if(patch.aiStatus!==undefined||patch.revision!==undefined)updateAI();if(patch.metalFinish)finishSelect.value=patch.metalFinish;state.bodies=state.bodies||[];state.selectedIds=state.selectedIds||[];if(propertyId&&!state.document?.features?.some(f=>f.id===propertyId))propertyId=null;q('#document-name').textContent=state.document?.name||'未命名设计';q('.empty-state').hidden=state.bodies.length>0||state.busy||!!state.interactionMode;q('.kernel-state').textContent=state.kernelReady?'内核就绪':'内核加载中';q('.kernel-state').classList.toggle('ready',!!state.kernelReady);q('.status-detail').textContent=state.selectedIds.length?`选中 ${state.selectedIds.length} / ${state.bodies.length}`:`${state.bodies.length} 个实体`;if(patch.status)api.setStatus(typeof patch.status==='string'?patch.status:patch.status.message||'');api.setBusy(state.busy);renderTrees();renderProperties();updateDisabled();updateViewControls();},setStatus(message,type='info'){q('.status-message').textContent=message;q('.statusbar').dataset.type=type;},setBusy(value,message){state.busy=!!value;q('.busy-overlay').hidden=!value;if(message)q('.busy-message').textContent=message;app.classList.toggle('is-busy',!!value);updateDisabled();},showError(message){api.setStatus(message,'error');const toast=element('div',{class:'notification error'});toast.append(element('strong',{},'操作未完成'),element('p',{},message),button('关闭',()=>toast.remove()));q('.notification-area').append(toast);},showInfo(title,message){const d=openDialog(title),text=element('div',{class:'info-content'},message);const foot=element('div',{class:'dialog-footer'});foot.append(button('知道了',closeDialog,'primary'));d.append(text,foot);},showProperties(feature,body){lastPropKey='';renderProperties(feature,body);},destroy(){closeDialog();translator.destroy();root.replaceChildren();}};
 renderRibbon();api.update();translator.translate();return api;
}












addTranslations({'开始设计':'Start designing','从顶部菜单创建模型，或打开已有文件。':'Create from the top menu, or open an existing file.','组合':'Group','拆散':'Explode','组合与拆散':'Group & explode','取消当前工具，返回箭头选择':'Cancel the current tool and return to arrow selection','将选中实体组合为复合体，保持各实体独立，不做布尔合并':'Group selected solids in a compound without Boolean fusion','将复合体中的实体拆成可独立选择和编辑的对象；单一实体请先分割':'Separate a compound into independently editable bodies; split a single solid first','当前对象只有一个实体，无法拆散；已融合的形状请先用分割工具':'This object has only one solid. Use Split first for fused geometry.'});

// Advanced tool field helpers are kept in advanced-tool-fields.js; JSON validation is handled by main before commit.
